### ISSUE TITLE
There is somtehing strange with referrer

### ISSUE THREAD

**Issue by jbleuzen** [electerious/Ackee#10]
I installed Ackee on one server, to test it in real situation.

Here is what I'm having on referer, there is definitively something wrong : 

![capture d ecran 2014-10-07 a 09 24 18](https://cloud.githubusercontent.com/assets/280681/4538656/2f00dc90-4df3-11e4-9476-c086fd323730.png)

**Comment by electerious** [comment]
*The old version has been deprecated.*
