### ISSUE TITLE
Add Country as detailed metric

### ISSUE THREAD

**Issue by BetaHuhn** [electerious/Ackee#103]
Seeing the languages of users is nice, but it would be more helpful to know where visitors are coming from. To do this in a privacy focused way you could get the country from the IP address with something like [geoip-country](https://www.npmjs.com/package/geoip-country) and save only that to the DB. With this module everything would happen locally and you wouldn't need a third party service.

**Comment by BetaHuhn** [comment]
I created a PR (#105)  that adds the country as a metric

**Comment by electerious** [comment]
Thanks a lot 👏 I hope I can take a closer look at it soon.

**Comment by abduramann** [comment]
Has this feature been added? My version does not have.

**Comment by electerious** [comment]
The feature hasn't made it into Ackee. You can read more about that decision in the PR: https://github.com/electerious/Ackee/pull/105#issuecomment-616098682
