### ISSUE TITLE
data-ackee-opts Uncaught SyntaxError: Unexpected end of JSON input in tracker.js

### ISSUE THREAD

**Issue by LickABrick** [electerious/Ackee#111]
I am using Nginx to inject the tracker.js (or crumble.js in my case) to my websites.
I have the following in Nginx:

```
sub_filter '</body>' '<script async src="https://analytics.mydomain.com/crumble.js" data-ackee-server="https://analytics.mydomain.com" data-ackee-domain-id="domain-id" data-ackee-opts="{"ignoreLocalhost": true}"></script>';
sub_filter_types text/javascript;
sub_filter_once on;
```

But now I get the following error in my console:

```
VM350:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f (crumble.js:1)
    at Object.2.platform (crumble.js:1)
    at i (crumble.js:1)
    at e (crumble.js:1)
    at crumble.js:1
    at crumble.js:1
    at crumble.js:1
```

Any clues on how to fix this?

**Comment by electerious** [comment]
I guess it has something to do with the quotes in `data-ackee-opts`. You should try to escape them:

```
sub_filter '</body>' '<script async src="https://analytics.mydomain.com/crumble.js" data-ackee-server="https://analytics.mydomain.com" data-ackee-domain-id="domain-id" data-ackee-opts="{\'ignoreLocalhost\': true}"></script>';
sub_filter_types text/javascript;
sub_filter_once on;
```

_or_

```
sub_filter '</body>' '<script async src="https://analytics.mydomain.com/crumble.js" data-ackee-server="https://analytics.mydomain.com" data-ackee-domain-id="domain-id" data-ackee-opts="{\"ignoreLocalhost\": true}"></script>';
sub_filter_types text/javascript;
sub_filter_once on;
```

**Comment by LickABrick** [comment]
> I guess it has something to do with the quotes in `data-ackee-opts`. You should try to escape them:
> 
> ```
> sub_filter '</body>' '<script async src="https://analytics.mydomain.com/crumble.js" data-ackee-server="https://analytics.mydomain.com" data-ackee-domain-id="domain-id" data-ackee-opts="{\'ignoreLocalhost\': true}"></script>';
> sub_filter_types text/javascript;
> sub_filter_once on;
> ```
> 
> _or_
> 
> ```
> sub_filter '</body>' '<script async src="https://analytics.mydomain.com/crumble.js" data-ackee-server="https://analytics.mydomain.com" data-ackee-domain-id="domain-id" data-ackee-opts="{\"ignoreLocalhost\": true}"></script>';
> sub_filter_types text/javascript;
> sub_filter_once on;
> ```

Just solved it myself too. Guess you always fix an issue when you ask someone for help.
Thanks for the fast response though ;)
