### ISSUE TITLE
Rough estimate of storage required?

### ISSUE THREAD

**Issue by donmccurdy** [electerious/Ackee#120]
Hi! I really like the concept of Ackee and your overall approach. What's less obvious to me is, how much might this cost to self-host? I know roughly how much traffic my domains get now, and roughly what hosting generally costs. But I don't know how Ackee stores events internally, or how much it aggregates historical data.

Does Ackee store one entry per visit, indefinitely? Or is there rolling aggregation to more compact daily/weekly/monthly storage? Can you give a rough estimate of how much disk space a MongoDB instance should need, per [some unit of traffic or time]?

Mainly, I'd like to be able to know (for X pageviews / day) whether I can run Ackee on a cheap-or-free 512MB instance, or if I need the larger $10-20/month instances.

Thanks!

**Comment by electerious** [comment]
I'm running Ackee with 12 sites since a year. It has a total of ~180k visits (each visit stores a record; there's no compression or optimisation right now). The MongoDB folder weights ~180MB. I hope that helps :)

**Comment by donmccurdy** [comment]
Ok, thank you for sharing! Unfortunately I can't self-host in a cost effective way at 1 KB/visit, but if there were other options in the future I'd be interested. Deleting individual visit data after N days would be fine for me, personally, if there were a daily summary I could reference in the future.

**Comment by electerious** [comment]
I don't think that the MongoDB folder will grow at 1 KB/visit. It would be interesting to know what size others have and if it's necessary to add optimisation.

**Comment by electerious** [comment]
Update: My folder includes diagnostic data. It's possible to turn the MongoDB diagnostic off to reduce the size of the folder.

**Comment by electerious** [comment]
Update: The folder also included the Ackee demo installation. Turns out that my installation isn't as big as I thought 😃

**Comment by donmccurdy** [comment]
Sounds promising! Do you have a better sense of what the per-visit data growth looks like, or is it hard to clean that out of the estimate?

**Comment by electerious** [comment]
Still not sure what's the best way to show the data usage, but here's the result of running `db.getCollection('records').stats()`. The records collection contains most data. I hope this helps.

![data](https://user-images.githubusercontent.com/499088/96365222-413c1300-113f-11eb-8fc9-b3a71e5c16dc.png)
