### ISSUE TITLE
Mixed content warning

### ISSUE THREAD

**Issue by samr28** [electerious/Ackee#121]
One of the XMLHttpRequests in the tracker seems to try and send a request over http even if the site was loaded over https which throws an error and prevents data collection. It can be fixed by including the following meta tag but ideally you shouldn't need this.
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"> `

It's hard to see what's exactly causing this as the tracker is minified but hopefully the second screenshot helps. 

Also, I have my server running behind a nginx proxy using the provided config, maybe there's an error in there with the headers?

![mixedcontent](https://user-images.githubusercontent.com/3688992/82920309-c1699e00-9f3c-11ea-94bc-5c8630926f07.png)
![image](https://user-images.githubusercontent.com/3688992/82920193-9c752b00-9f3c-11ea-97ee-8d5935f8e73b.png)

**Comment by electerious** [comment]
How are you including the tracker on your site? Ackee should use `https` when the server URL uses https: https://github.com/electerious/ackee-tracker#usage

**Comment by samr28** [comment]
I had included it with http src url and data-ackee-server instead of using the https one
![image](https://user-images.githubusercontent.com/3688992/82924591-2c69a380-9f42-11ea-9dc4-53aa418bd835.png)
