### ISSUE TITLE
Privacy Policy template

### ISSUE THREAD

**Issue by ThaneshR** [electerious/Ackee#122]
Hello,

I was wondering if there's a privacy policy template available.

Here's an example from [Simple Analytics](https://docs.simpleanalytics.com/your-privacy-policy).

Thanks,
Thanesh

**Comment by electerious** [comment]
You can basically use the privacy policy provided by Simple Analytics. Everything they say applies to Ackee. I think it's a good idea to provide a similar one for Ackee! :)

**Comment by shaftoe** [comment]
This looks good, actually I think might be a good idea to add at least a link to this in the FAQ? I think basically every Ackee needs to know (even if they don't know they do 😆)

**Comment by electerious** [comment]
Here we go: https://docs.ackee.electerious.com/#/docs/Privacy%20Policy
