### ISSUE TITLE
Edge Browser not working?

### ISSUE THREAD

**Issue by MatthK** [electerious/Ackee#123]
It seems that the Edge Browser from Microsoft is not showing up in my stats. But when I check in the console (pressing F12) of Edge, there is no Warning or Error, yet although I do browse my site with Edge, nothing shows up in the stats.

**Comment by electerious** [comment]
I've tested it with Edge 83.0.478.37 and it seems to work fine. Are you seeing a blank page or just empty charts?

**Comment by MatthK** [comment]
I updated to the lasted Edge (I still had Version 44 sth) and now I can see the pages showing up when I browse the website.
