### ISSUE TITLE
Providing all statistics on a single page

### ISSUE THREAD

**Issue by maxok** [electerious/Ackee#125]
Hello,

I have just installed Ackee analytics and it looks really impressive. I just wanted to know, if there is possibility through configuration to show all the statistics on a single page? For small websites, I think this would be a useful feature.

**Comment by electerious** [comment]
It's currently not possible, but I'm already working on a domain view for the next major release :) Keep an eye on [@getackee](https://twitter.com/getackee) to stay up-to-date.
