### ISSUE TITLE
Update Node.js version to v14 in Docker image

### ISSUE THREAD

**Issue by PabloSzx** [electerious/Ackee#126]
There are performance optimizations in updating the Node.js version to v14 (due to v8 8.1 update).

[More info here](https://medium.com/@nodejs/node-js-version-14-available-now-8170d384567e)

**Comment by electerious** [comment]
That's a good idea. I've already updated to v12 and might go up to the current version soon. It will be part of the next major release: https://github.com/electerious/Ackee/blob/feature/graphql/Dockerfile
