### ISSUE TITLE
Showing no systems, devices, browsers, or sizes

### ISSUE THREAD

**Issue by BlakeEric** [electerious/Ackee#127]
First of all, thanks for all your work on this! I love Ackee so far.

I have deployed Ackee on Heroku and added config vars as specified in the docs. Page and referrer data is being updated, but detailed data on systems, browsers, devices, or sizes is always unavailable. Any tips would be much appreciated!

<img width="550" alt="Screen Shot 2020-06-26 at 9 34 19 AM" src="https://user-images.githubusercontent.com/10524212/85880047-39bbbd00-b790-11ea-80ae-bb968fe5ecaa.png">

**Comment by PabloSzx** [comment]
If you are using the script tag in html you have to specify `detailed` like this example
```html
<script async src="https://example.com/ackee-tracker.min.js" 
data-ackee-server="https://example.com" 
data-ackee-domain-id="hd11f820-68a1-11e6-8047-79c0c2d9bce0" 
data-ackee-opts='{ "ignoreLocalhost": true, "detailed": true }'></script>
```

**Comment by electerious** [comment]
Systems, devices and so on are considered as personal data. You should ask your users before enabling the detailed tracking as described by @PabloSzx. Here's more about it: https://github.com/electerious/Ackee/blob/master/docs/Anonymization.md#personal-data 

I recommend to use the [programmatic approach](https://github.com/electerious/ackee-tracker#programmatic). It allows you to set `detailed` to `true` only when the user agreed (e.g. via a privacy message on your website).

Ackee should better communicate this in the UI. I've added it to my notes 😊

**Comment by BlakeEric** [comment]
Thank you, that's very helpful!
