### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by MatthK** [electerious/Ackee#130]
I understand that the data is reset using the UTC time zone. But since I leave east of the UK, the dashboard always shows the new day with 0, while "yesterday" keeps growing. So I have an 8 hour window where I see 0 new visitors, but the previous day keeps changing. 

It's not really a big issue, but it would be nice if the dashboard could switch using UTC, or if I can set a time zone and then the data is aggregated by that value.

**Comment by electerious** [comment]
See #88 for more information. A fix is planned for v2 and has a high priority. The implementation right now basically ignores timezones. This should be fixed with the new API.
