### ISSUE TITLE
Provide migration path from Google Analytics

### ISSUE THREAD

**Issue by MKorostoff** [electerious/Ackee#131]
Hello, I'm currently working to adopt Ackee on my personal websites. I have previously been using google analytics. Google analytics allows data to be exported in a variety of formats, including CSV. I think it would be helpful if ackee included some utility for importing this data. If the maintainer(s) are interested in this feature, I would be happy to write it and contribute the code.

**Comment by electerious** [comment]
Thanks for the suggestion, but it's currently not planned to add an import feature to Ackee as I'm trying to keep it as lightweight as possible. You could write the CSV directly into the database if an import is need.

**Comment by MKorostoff** [comment]
Sure, no worries, I definitely respect the desire to be lightweight. I'll post whatever code I come up with here in this thread, maybe someone will find it useful, but you don't have to merge it. Cheers!
