### ISSUE TITLE
Read-only access

### ISSUE THREAD

**Issue by marcusbuffett** [electerious/Ackee#134]
It would be great if there was some way to give read-only access. Either accounts that can only read, or ideally (for me), a login-free read-only site. I've somewhat gotten around this by prohibiting DELETE commands, since deleting a domain is the only negative action I could see a malicious user doing currently, but would be nice to have a supported solution.

If it matters, the reason for this is trying to have open metrics for a site I run, [Open Startup-style](https://baremetrics.com/open-startups)

**Comment by electerious** [comment]
There's a hidden demo mode (`ACKEE_DEMO=true`) that could be modified. It basically disables commands that modify data and adds a [username and password to the login](https://github.com/electerious/Ackee/blob/master/src/ui/scripts/components/overlays/OverlayLogin.js#L17) (ackee, 123456). It also fills the database with views.

Not exactly what you're looking for, but it might be easy to modify it.

**Comment by marcusbuffett** [comment]
Interesting, I may try to modify that, thank you
