### ISSUE TITLE
Custom fields, “dimensions”, etc.

### ISSUE THREAD

**Issue by qqilihq** [electerious/Ackee#135]
Hi there,

is there any mechanism to send and store additional information? (I think on Google Analytics it would be considered a “custom dimension”.)

Example what I would be interested in:

* easily get number of views for a collection of e.g. “blog posts” in the database -- if I could store the blog post `id`, this would be a simple lookup on the DB/API

* get statistics per tenant -- imagine we have `bob.blog.com`, `alice.blog.com`, etc. I would like to easily get the stats just for one of these users (for me, API, or even direct DB access would suffice for now).

Love to hear your opinion or feedback. Understand, that this might conflict with your “anonymity” goals though.

**Comment by electerious** [comment]
It's not possible right now and I don't think that Ackee will be a good fit for custom fields. I would only implement it if the data would be available via the interface and that could get very complex with custom data.

It's planned to have something like "Events" in the future. Not sure how the final version of those will look, but maybe that's something for you: https://github.com/electerious/Ackee/pull/101

**Comment by qqilihq** [comment]
Thanks for the feedback!
