### ISSUE TITLE
Web vitals logging

### ISSUE THREAD

**Issue by tobimori** [electerious/Ackee#136]
Wouldn't it be nice to allow Ackee to track [web vitals](https://web.dev/vitals/)?

Frameworks like [Next.js](https://nextjs.org/blog/next-9-4#integrated-web-vitals-reporting) allow to include a function that reports those web vitals from users, tho I didn't find an analytics software that supports that and would work fine for me.

**Comment by electerious** [comment]
That's a great idea! I will add it to the list of potential features.

**Comment by electerious** [comment]
It's still something I'm interested in, but I'm closing this issue in favour of another one: https://github.com/electerious/Ackee/issues/207
