### ISSUE TITLE
Cannot login via custom domain

### ISSUE THREAD

**Issue by emschwartz** [electerious/Ackee#144]
I have Ackee v2 running on Heroku and I'm using Cloudflare to point a subdomain of a custom domain at it. I can login just fine using the `.herokuapp.com` domain, but when I try to login using the custom domain I'm seeing:

```
Not found
[552]</n.default@https://<custom domain>/index.js:124:127951
```

And it looks like it's getting a 404 error when trying to POST to the `/tokens` endpoint.

Any ideas why this might be happening?

**Comment by electerious** [comment]
There shouldn't be request to `/tokens` anymore. This sounds like a caching issue / old JS file.

**Comment by emschwartz** [comment]
Doh! That was it. Thanks!
