### ISSUE TITLE
Leafs are too wide to be displayed on iPhone

### ISSUE THREAD

**Issue by jbleuzen** [electerious/Ackee#15]
Just tested ackee on my iPhone and the leafs are wider than the iPhone screen :
 
![img_20141010_042153](https://cloud.githubusercontent.com/assets/280681/4587597/149161b6-502f-11e4-878b-03026fd52bfe.jpg)

Tested with chrome emulator, working fine on iPhone 6+ :p

**Comment by electerious** [comment]
*The old version has been deprecated.*
