### ISSUE TITLE
View data for more than 2 weeks ago

### ISSUE THREAD

**Issue by hardfire** [electerious/Ackee#150]
First of all thank you for the work in the app. 
I've been using ackee for the last month and realized that the UI doesn't have a way to see "daily" data more than 2 weeks back. Is it possible that's the case or maybe i've been missing an hidden option in the interface?

![image](https://user-images.githubusercontent.com/513457/91937621-065a5900-ed12-11ea-962d-03ff0cf40ab1.png)

**Comment by Go-Merk** [comment]
I can't confirm myself but, if you go on the **insights** tab on the top of the page and select the metric you want to know, you will see a small floating bubble fixed on the bottom of the page, there you can select older data. 👍

I do believe that it should have a small arrow like this, would facilitate tho:
![image](https://user-images.githubusercontent.com/54755295/91968353-e9f6f600-ecea-11ea-9c55-86d397ea1de4.png)

**Comment by hardfire** [comment]
Interesting,
I cannot see this arrow on demo as well
![image](https://user-images.githubusercontent.com/513457/91977217-05412000-ed42-11ea-8f9a-13fa7094695d.png)

**Comment by Go-Merk** [comment]
oh no, it's not on the demo, i just put there using the elements to show how i think it should be done, adding the svg element that's all what I did, no such thing was implemented but I hope it will, sorry for the mix up. 😅 

Just for clarifying:

![image](https://user-images.githubusercontent.com/54755295/91981052-a0b0a180-ecfe-11ea-98fd-71bb3a0d891f.png)

Then, select any stat you want:

![image](https://user-images.githubusercontent.com/54755295/91981223-deadc580-ecfe-11ea-9d30-beca1d4cb6c2.png)

Voilá!

**Comment by electerious** [comment]
It's indeed not possible right now to see previous weeks. You can only group by day, month or year. Going back in time is a feature that has been planned size the beginning, but it doesn't have a high priority.

@Go-Merk Thanks for the suggestion!

Tip: You can use the API to get more data if you really want to :)

Please follow this issue if you want to stay up-to-date: https://github.com/electerious/Ackee/issues/39
