### ISSUE TITLE
Upgrade to V2.0.1

### ISSUE THREAD

**Issue by MatthK** [electerious/Ackee#164]
I just tried to upgrade Ackee to the latest version and pulled the latest docker image.

When I started the container pointing to the existing Mongodb I don't see any of the previously setup domains and that data. Is there a way to preserve the previous history or do I have to start new with all the existing sites?

**Comment by electerious** [comment]
Are you sure that your configuration and MongoDB collection is the same as before? Ackee will reuse all the previous data as long as you're connecting to the same MongoDB collection.

**Comment by MatthK** [comment]
After checking again, I noticed that I missed the '-marks around the mongodb-string. When I added them at the beginning/end, it did pick up the values in the db.
