### ISSUE TITLE
Clarify that focusing 'Domain ID' or 'Embed code' box copies to clipboard

### ISSUE THREAD

**Issue by tkw1536** [electerious/Ackee#166]
When focusing the 'Domain ID' or 'Embed ID' fields in the Domain Edit Modal their content is copied to the clipboard. 

This is a great feature, however it lacks any kind of indication in the UI or the documentation. 
I only found out about it because I wanted to implement this feature myself and found that it already existed when looking at the source code. 

It would be great if some text like `Click to Copy` could be added to the interface to indicate to users that this feature exists.

**Comment by electerious** [comment]
Definitely. Some kind of popup or notification would be great.

**Comment by electerious** [comment]
https://user-images.githubusercontent.com/499088/102715093-3898c200-42d3-11eb-8861-06f77a623ba6.mov

Implemented. It's currently in the events branch and will therefore be part of the next minor/major release.
