### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by Maronato** [electerious/Ackee#170]
Hello! First of all, thank you for creating Ackee. Such a beautiful tool and a breeze to install :)

That said, it seems to be consuming an unusually high amount of memory for a node app. A single instance is taking an average of 170mb just to exist, with next to no traffic running into it. My other node apps consume about half as much memory. In fact, Ackee is currently the third most memory-hungry app running on my cluster with 30+ services.

I'm running version 2.0.0.

Below are the stats of the last 24 hours for a single container running Ackee. CPU and network are ok and, as you can see, it received next to no traffic over this period.

The spike in usage at the end represents the moment I logged into it to confirm the current version.

![CleanShot 2020-10-09 at 13 45 42@2x](https://user-images.githubusercontent.com/19658460/95609971-f41cba80-0a35-11eb-8836-958b07c030f7.png)
![CleanShot 2020-10-09 at 13 53 28@2x](https://user-images.githubusercontent.com/19658460/95610652-06e3bf00-0a37-11eb-82b9-0a8b95dcc128.png)
![CleanShot 2020-10-09 at 13 51 39@2x](https://user-images.githubusercontent.com/19658460/95610457-be2c0600-0a36-11eb-9608-638d6d75785d.png)
![CleanShot 2020-10-09 at 14 11 57@2x](https://user-images.githubusercontent.com/19658460/95612252-7d81bc00-0a39-11eb-8e4b-57737bf5725d.png)

**Comment by electerious** [comment]
Thanks for letting me know. It would be interesting to see what causes this high usage.

Will it stay at ~150mb or does the memory usage grow?

**Comment by BetaHuhn** [comment]
I have also noticed that Ackee recently started consuming a lot more memory than before. I don't know since when. I am running v2 for a few weeks now and don't think it was this high when I upgraded but I am not 100% sure. It currently consumes around 100 - 150 mb.

**Comment by electerious** [comment]
It looks like that the [feature/serverless](https://github.com/electerious/Ackee/tree/feature/serverless) branch uses a lot less memory. This could be because I'm now building the source files in a different step, instead of requiring all build files (babel, sass, etc.) in the server. They could unnecessary fill the memory even when they're only used once. From ~126mb to ~50mb.

**Comment by electerious** [comment]
The serverless branch has been merged into develop and will be part of the next release. Please let me know when the usage is still high.
