### ISSUE TITLE
Deployment to Vercel

### ISSUE THREAD

**Issue by Burnsy** [electerious/Ackee#174]
Hi, I just tried to push this to Vercel and it looks like it gives an error due to the package.json node engine.

![image](https://user-images.githubusercontent.com/15834048/97301291-8226dc80-184f-11eb-8c84-36f86604d46c.png)

Any thoughts on how to get this deployed on Vercel?

It seems to be erroring even before env's are set. 

Thanks!

**Comment by electerious** [comment]
Looks like Vercel only supports Node.js 10 and 12, but not version 14. You can try to fork Ackee and change the engine in the package.json. Here's what Vercel recommends: 


```json
{
  "engines": {
    "node": "12.x"
  }
}
```

More: https://vercel.com/docs/runtimes

Let me know if this fixes the issue. Not sure if Ackee still works with Node.js 12.
