### ISSUE TITLE
Daylight savings time bug

### ISSUE THREAD

**Issue by emschwartz** [electerious/Ackee#181]
This is definitely not an important issue but there seems to be a small daylight savings time bug where it shows the views from the day as both today and yesterday.

![image](https://user-images.githubusercontent.com/3262610/97829616-8e1ffd80-1c98-11eb-9e74-ebc4a301644b.png)

**Comment by electerious** [comment]
Oh no, not yet another time(zone) issue 😃 Those are the worst.

Thanks for letting me know! Can you specify when exactly this happens? Only during midnight? Does it work in the middle of the day?

**Comment by emschwartz** [comment]
I saw it at around 11pm the day the clocks were switched (it was switched at 2am that morning). I didn't see whether it also showed up during the day or just between 11pm and midnight, sorry! I know these are super annoying.

**Comment by electerious** [comment]
I couldn't reproduce this bug, but please let me know when this happens, again.
