### ISSUE TITLE
[Help / How-To] Ignore domains (e.g. from Vercel)

### ISSUE THREAD

**Issue by cupcakearmy** [electerious/Ackee#183]
First of all thanks for the very nice tool you have built ❤️

I have a question: My wesites are often deployed on Vercel and there are some entries that pop up in the stats that are not real users. Is there any whay to white/black list domains to track? I'm quite sure it's the service od Vercel that takes screenshots for their dashboard.

<img width="572" alt="Screenshot 2020-11-03 at 00 31 14" src="https://user-images.githubusercontent.com/14948823/97930816-89c51480-1d6c-11eb-85ac-421f8522d6f3.png">

Thanks :)
Btw feel free to close, don't want to pollute your issues xD

**Comment by electerious** [comment]
Looks like the [Vercel bot has a User-Agent](https://github.com/vercel/vercel/discussions/5095). We could use it to filter it out 😊

There's already some logic in ackee-tracker to do so: https://github.com/electerious/ackee-tracker/blob/develop/src/scripts/main.js#L42 PR welcome.

**Comment by cupcakearmy** [comment]
Makes sense. Although `/bot|crawler|spider|crawling/i` should already include `Vercelbot` right?

**Comment by electerious** [comment]
You're right! I just released the new version of `ackee-tracker`. It includes the bots fix. You can install this package/version manually or wait for the next Ackee release. Let me know if it's not fixed after the update.

**Comment by cupcakearmy** [comment]
I believe it's on develop on docker right? what is the timeline on the latest tag? otherwise I'll just wait for the next release

**Comment by electerious** [comment]
Just released v2.3 :)
