### ISSUE TITLE
Yarn install documentation missing something?

### ISSUE THREAD

**Issue by aske-cph** [electerious/Ackee#188]
Hi everyone,

I go to the install docs: https://docs.ackee.electerious.com/#/docs/Get%20started#without-docker

Since i don't use Docker i just want to install with Yarn. (_Use npm normally but yarn seems easy enough_)

1 )  I install the dependencies as prescribed
2)  I add the config
3)  Then the next step is just "Yarn" ???

There is no step to pull the project, since i don't use Yarn normally i just guessed it's `electerious/Ackee`

Isn't there something missing here? I tried `"Yarn Add electerious/Ackee"` - which worked but the next step still doesn't work.

4) Because in the next step it just says "Run Ackee with `Yarn Start`". Run what exactly? 

I get:

`error Command "start" not found.`

There is no "start" command in my package_json, and what exactly should that command run?

Can anyone point out if i am missing something in the docs?

Thanks for what looks like an awesome project anyway :)

**Comment by electerious** [comment]
We should add the info that you need to pull the project before you continue with step 2. Everything you create should be within the pulled project (like the `.env` file).

`yarn` => That's correct. Running `yarn` inside a project is like running `npm install`.

`yarn start` => The project contains a start command and will execute when running this command.

I hope that helps.

**Comment by aske-cph** [comment]
Ah i see. Worked after cloning the repo. Pulling with a manager will overwrite .env files so cloning / copying with custom build is necessary.

Thank you for the quick answer!
