### ISSUE TITLE
"Systems", "Devices", "Browsers", etc. stats stay empty

### ISSUE THREAD

**Issue by sfermigier** [electerious/Ackee#190]
**🐞 Describe the bug**

I've installed Ackee a few months ago for a few sites and it works as advertised, except for the five advanced "insights", like "Systems", "Browsers" and so on which stay at 0.

I couldn't find any clue on how to activate this feature in the documentation.

**🖼️ Screenshots**

<img width="862" alt="Screen Shot 2020-11-12 at 09 21 22" src="https://user-images.githubusercontent.com/271079/98914175-a11ca400-24c8-11eb-9e93-efa02551e4d4.png">

**⚙️ Environment**

 - Installation: Heroku
 - Ackee version: recently upgraded to 2.3.0

**Comment by electerious** [comment]
See https://github.com/electerious/Ackee/issues/127

Ackee still does a bad job explaining why this data is missing in the UI. We should improve this.

**Comment by electerious** [comment]
I've created a new issue for this: https://github.com/electerious/Ackee/issues/192
