### ISSUE TITLE
Nginx reverse proxy documentation clarification?

### ISSUE THREAD

**Issue by aske-cph** [electerious/Ackee#191]
I don't find the reverse proxy docs that extensive for nginx novices? 

Can anyone point the failure in understanding? Thanks in advance!

1) I have set up and installed everything on the server, ackee is running on  http://localhost:3000 on production

2) I have the domain : _domaintest.com_ . Already i can access the interface via domaintest.com:3000 - but i need to both be able to send data from the tracker and access through ssl so i need to make a "_reverse proxy_" - what i find mystifying though is the example. 

The example is for "example.com" which would be the nginx.conf file 
for domaintest.com in my case - but editing this and all data is just proxied to Ackee - so i just get a blank page.

3) This is what i add to my domaintest.com nginx config file inside the location block

        add_header          Access-Control-Allow-Origin "*" always;
        add_header          Access-Control-Allow-Methods "GET, POST, PATCH, OPTIONS" always;
        add_header          Access-Control-Allow-Headers "Content-Type" always;
        add_header          Strict-Transport-Security "max-age=31536000" always;
        add_header          X-Frame-Options deny;
        proxy_pass          http://localhost:3000;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect      off;
        proxy_buffering     off;
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for; 

I am surely missing something because this doesn't seem to "_gives any domain permission to access Ackee._" but instead just proxies everything to Ackee, so my front page ends up being the Ackee page (but blank).

In my mind it seems like i need a new custom domain that is routed only to localhost:3000, but then i can't use the domain for anything else?

**Comment by BetaHuhn** [comment]
Hey, I don't know if I am fully understanding your problem, but here's how I am doing it with nginx and one domain:

I've setup a subdomain (e.g. ackee.domaintest.com) in my DNS which points to my server. Here's my nginx config file:

```nginx
server {
	listen 80;
	server_name ackee.domaintest.com;
	return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    client_max_body_size 5000M;

    root /path/to/ackee/folder;
    server_name ackee.domaintest.com;
   
    # ... all my SSL stuff

    resolver 8.8.8.8;

    add_header Access-Control-Allow-Credentials true;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';  
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
        proxy_pass_request_headers on;
    }
}
```

**Note:** I am using this configuration with a Let's encrypt SSL certificate.

Hope that helps, let me know if you have any questions.

**Comment by aske-cph** [comment]
Thank you very much! I copied your code and i works now. (_i stil don't generate any hits though, so i am still tinkering_)

I pretty much deduced that a subdomain was necessary but wasn't sure. I think the docs could be made a bit easier for people especially when coming from gAnalytics.

A text like this would clarify a lot on the top of the page, instead of the 1,2,3 on the bottom of the page:

Ackee is a simple analytics tool consisting of two parts. A node server running on the server of your choice, and a tracking script that talks to that server. The node server shows you the interface with analytics and receives the request from all of your sites, while the tracking script is set up on each site you want analytics for. Since normally your site and your analytics server is running on the same machine, a subdomain is needed that proxies all requests from that subdomain to the node server running locally on port 3000.

Looking forward to use this neat tool!

**Comment by electerious** [comment]
Great info. I've added the text to the Get started guide!
