### ISSUE TITLE
Indicate why detailed data is empty in UI

### ISSUE THREAD

**Issue by electerious** [electerious/Ackee#192]
**🐣 Is your feature request related to a problem? Please describe.**

It's confusing that Ackee displays no data for systems, devices, browsers, or sizes and doesn't explain why.

**💡 Describe the solution you'd like**

The empty state of detailed data widgets should be updated to include a notice that this feature needs to be enabled.

**📋 Additional context**

https://github.com/electerious/Ackee/issues/190
https://github.com/electerious/Ackee/issues/127

**Comment by BetaHuhn** [comment]
Hey, can I work on this?

**Comment by electerious** [comment]
Thanks for offering your help! I'm currently refactoring a lot of the UI for #40. I guess it's better to wait until all the changes are done.

**Comment by electerious** [comment]
Explanation has been added! It will be part of the v3 release.
