### ISSUE TITLE
Not found warnings after upgrading

### ISSUE THREAD

**Issue by Antidote00** [electerious/Ackee#200]
**🐞 Describe the bug**

I tried to upgrade from v1.3.0 to 2.4.0 using docker compose. I used the following commands:

* `docker-compose down`
* `git pull`
* `docker-compose rm`
* `docker-compose pull` 
* `rm -rf ./data/`
* `docker-compose up`

On the frontend side, everything seems good, however starting the docker without `-d` results in a lot of similiar warnings in short time intervals. Namely:

```
ackee    | [Ackee] › ⚠  warning   Unknown record
ackee    | [Ackee] › ⚠  warning   `/domains/f566ef01-724a-4d28-996f-d580d6e1ebf9/records/7803aed5-1c5a-45a1-9d91-71e1b659fd1d` not found
ackee    | [Ackee] › ⚠  warning   `/domains/f566ef01-724a-4d28-996f-d580d6e1ebf9/records/004f2a9d-4d23-4230-9832-0de4400d466e` not found
ackee    | [Ackee] › ⚠  warning   `/domains/f566ef01-724a-4d28-996f-d580d6e1ebf9/records/7803aed5-1c5a-45a1-9d91-71e1b659fd1d` not found
ackee    | [Ackee] › ⚠  warning   `/domains/f566ef01-724a-4d28-996f-d580d6e1ebf9/records/004f2a9d-4d23-4230-9832-0de4400d466e` not found
```

**📚 To Reproduce**

Install old Version of Ackee and try to upgrade with the commands:

* `docker-compose down`
* `git pull`
* `docker-compose rm`
* `docker-compose pull` 
* `rm -rf ./data/`
* `docker-compose up`

Even after completely deleting the Ackee folder, again checking out the newest version and running `docker-compose up`, the warnings remain.

**💡 Expected behavior**

I would expect no warnings refering to old domain entries as i have deleted the ./data folder holding the database information.

**⚙️ Environment**
 - Docker Compose on Debian 10
 - Ackee version: 1.3.0 to 2.4.0

**📋 Additional context**

Could you please explain how to make a proper upgrade of Ackee? Thanks in advance.

**Comment by electerious** [comment]
You just have some people which are still on your site and are using the old API to track visits 😊 That's either because your sites include an old version of ackee-tracker or because your users haven't reloaded your site in a while.

Those warnings usually disappear in some days.

Hope that helps!

**Comment by Antidote00** [comment]
Oh okay. Thank you very much. The number of warnings was soo high. However it seems the most recent page we are hosting is very popular. I will close this and come back for real problems ;). Thanks for the great work and application.
