### ISSUE TITLE
Hosting Ackee on Netlify uses up the request quota (> 125,000 reqs) even with minimal usage

### ISSUE THREAD

**Issue by golddranks** [electerious/Ackee#202]
**🐞 Describe the bug**

After using Ackee for only a week on Netlify Functions (Level 0, i.e. free tier), it has used up 101,158 requests of the 125,000 request quota. This is an outrageous amount, considering that the dashboard showed only 404 views in total and 58 seconds of average duration. When visiting the site it's deployed on ( https://saunoja.jp ), the script seems to work well enough, sending requests every some 15 seconds.

At the moment it used up all of my level 0 resources.

**📚 To Reproduce**

At the moment I have the dashboard deployed at https://analytics.saunoja.jp and the site itself at https://saunoja.jp. I'm able to see how the request count is rising at a lot quicker speed that I'd expect from the view count.

I have no idea whether the bug reproduces if I do a fresh install of Ackee as a new Netlify site; I'd like to confirm whether this is expected behaviour or not before doing further testing.

**💡 Expected behavior**

I would expect the request count to be roughly equal to the amount of views ✕ (the average duration / 15 seconds) = in the neighborhood of 1500–1600 requests. So somehow, it sent 60–70 times the amount of requests I was expecting.

**🖼️ Screenshots**
(These screenshots were recorded later than the numbers above, but they demonstrate the same problem.)

Netlify Functions control panel:
<img width="972" alt="スクリーンショット 2020-12-06 14 09 55" src="https://user-images.githubusercontent.com/2675542/101272130-c9987500-37cc-11eb-89be-0638b504d8ab.png">

Ackee dashboard:
<img width="1220" alt="スクリーンショット 2020-12-06 14 09 27" src="https://user-images.githubusercontent.com/2675542/101272132-cdc49280-37cc-11eb-93ae-1763fed68ba6.png">

**⚙️ Environment**
 - Installation: Netlify
 - Ackee version:  v2.4.0

**Comment by electerious** [comment]
That sounds like a lot. It's possible that it's because of users leaving your website open in the background. The durations aggregation only shows visits with a duration up to 30min, but `ackee-tracker` keeps sending data. I've seen a lot of those requests in my logs. That's why Ackee ignores those "inactive" visits. One user could generate 5.760 requests in one day. Still … 101,158 requests is a lot. Are you using the menu bar app or a widget or something else that requests data?

I think it would be a good idea to decrease the amount of requests in `ackee-tracker`. We could a) stop after 30min b) Decrease the interval as time passes (e.g. the longer the website is open the lower the interval).

**Comment by thecodrr** [comment]
It should be based on user interaction. If the page is open in a background tab and no one is interacting the interval should stop after 30min.

As soon as the user interacts, the interval starts again. Basically, after every 30 min, the tracker should check if the user interacted with the website recently, if he did we restart the interval. If he didn't, the interval pauses until the user interacts again.

Now what would count as interaction? I think window.onclick, window.onscroll should be good enough.

**Comment by azrikahar** [comment]
Just chiming in on the "what would count as an interaction" aspect, perhaps the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) is a feasible approach? We can then halt the requests if it is not an active tab/window, which feels like can even be a more accurate representation of viewing duration as well.

**Comment by thecodrr** [comment]
Yes. Page Visibility API would be most effective for this. It is compatible in all browsers so that won't be an issue. However, I don't know why it's not used in other analytics trackers. Is it privacy invading?

**Comment by electerious** [comment]
The Page Visibility API sounds like a good solution. We could check `document.hidden` before updating the duration. A PR for ackee-tracker is welcome.

**Comment by PierreSchwang** [comment]
Because https://github.com/electerious/ackee-tracker/pull/30 is merged, should this issue be closed @electerious?

**Comment by golddranks** [comment]
Is it released yet? If it is, I'd like to try updating and will report back here, but feel free to close this meanwhile.

**Comment by electerious** [comment]
I've just published a new pre-release of ackee-tracker (`npm install ackee-tracker@next`) and a develop version Ackee. The [develop version](https://github.com/electerious/Ackee/tree/develop) includes the pre-release of ackee-tracker and therefore the background update change. The develop version is also available [via Docker](https://hub.docker.com/layers/68167147/electerious/ackee/develop/images/sha256-43aabd8bc9cc3804826a4ba161b27c430c2d93290ce5e97da5da2193d4168bb2?context=explore).

Will do some testing in the next days to see if everything works fine!

**Comment by golddranks** [comment]
I also tried deploying the new version here: https://saunoja.jp

**Comment by electerious** [comment]
It's live 😊 https://github.com/electerious/Ackee/releases/tag/v3.0.6
