### ISSUE TITLE
Import/export functionality

### ISSUE THREAD

**Issue by marchellodev** [electerious/Ackee#204]
I think it would be really cool to be able to export and import analytical data from ackee. It would be useful when migrating from one server to another or just from any other analytical service.

There is no need to add service-specific importing, just a generic format (csv, json, xml, whatever) would be really useful.

**Comment by electerious** [comment]
There's currently no plan to add this feature, but the API and database should provide everything to build such a service.

I'm sure there's a MongoDB exporter that can be used to get the data out of Ackee. The `records` model is quite simple and it shouldn't be hard to convert it into a CSV or JSON. This could also work in the other direction.

Would be great to see such a service for Ackee. It's just not something that will be part of the main project :)
