### ISSUE TITLE
Ackee MongoDB error

### ISSUE THREAD

**Issue by JustNZ** [electerious/Ackee#208]
**🐞 Describe the bug**

After setting up ackee over docker I'm not able to log in.

The log shows that there is a problem with MongoDB:
exception: Unrecognized pipeline stage name: '$count'

**📚 To Reproduce**

- Created a new database and user on my MongoDB instance
- Configured ackee with db and user details
- Unable to Login

**💡 Expected behavior**

Successful login

**🖼️ Screenshots**
![image](https://user-images.githubusercontent.com/51332147/103638832-bd2f4580-4f4d-11eb-8596-615ea4574bb7.png)

**⚙️ Environment**
 - Installation: Docker
 - Ackee version: latest

**📋 Additional context**

Docker Log:
[container.log](https://github.com/electerious/Ackee/files/5769748/container.log)

**Comment by JustNZ** [comment]
The log shows up to MongoDB errors:
1. exception: FieldPath 'Europe/Berlin' doesn't start with $
2. exception: Unrecognized pipeline stage name: '$count'

The error even appears on version 2.4.0

**Comment by electerious** [comment]
It sounds like an unsupported MongoDB version. Which one are you using?

**Comment by JustNZ** [comment]
Hey,
you are right.
My MongoDB Image used an old version.
Works now. 

Thanks!
