### ISSUE TITLE
NO_RESPONSE_FROM_FUNCTION

### ISSUE THREAD

**Issue by RiversideRocks** [electerious/Ackee#210]
```
NO_RESPONSE_FROM_FUNCTION

[586]</n.default@https://ackee-eight.vercel.app/index.js:136:152632
```

Tried to deploy Ackee to vercel and got an error on signin. How can I fix this?

**Comment by lavandalabs** [comment]
@RiversideRocks did you solve this?

**Comment by RiversideRocks** [comment]
Yep, I checked my logs on Vercel, turned out it was a mongodb auth issue.
