### ISSUE TITLE
Unable to use wildcard Access-Control-Allow-Origin in Version 3

### ISSUE THREAD

**Issue by tkw1536** [electerious/Ackee#220]
**🐞 Describe the bug**

When using `Access-Control-Allow-Origin: *` on v3 ackee-tracker can not record any visits.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://ackee.example.com/api’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).
```
The console furthermore points to [MDN to learn more](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials).

**📚 To Reproduce**

1. Deploy ackee with an `Access-Control-Allow-Origin: *` header.
2. Setup `ackee tracker` on any page
3. Look in the browser console to see two errors:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://ackee.example.com/api’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).
```

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ackee.example.com/api. (Reason: CORS request did not succeed).
```

Using Firefox 84 on Linux; haven't tested other browsers but I would expect the behavior to be the same.

**💡 Expected behavior**

The cross-origin request does not fail and the visit is recorded. 

**🖼️ Screenshots**

**⚙️ Environment**
 - Installation: Docker-Compose
 - Ackee version: v3.0.2

**📋 Additional context**

A fix would be to allow users with `Access-Control-Allow-Origin: *` to not send credentials in Ackee Tracker. 
As this disables not tracking of own visits, I would suggest to simply re-add the old `ignoreOwnVisits` option; but this time with a default of true. I'll make an appropriate PR to ackee-tracker shortly.

**Comment by electerious** [comment]
I guess there're several things we could do:

- Don't recommend to use a wildcard, because it's not good anyway
- Return the current request URL instead of a wildcard when using `ACKEE_ALLOW_ORIGIN="*"` (similar to https://github.com/electerious/Ackee/blob/master/docs/SSL%20and%20HTTPS.md#advanced-configuration)
- Is it possible to catch the CORS header in the client? We could try it again with a notice that Ackee failed to ignore your own visits. I would prefer this solution instead of adding an option.

**Comment by electerious** [comment]
> - Return the current request URL instead of a wildcard when using `ACKEE_ALLOW_ORIGIN="*"` (similar to https://github.com/electerious/Ackee/blob/master/docs/SSL%20and%20HTTPS.md#advanced-configuration)

This won't work in serverless environments it seems.

> - Is it possible to catch the CORS header in the client? We could try it again with a notice that Ackee failed to ignore your own visits. I would prefer this solution instead of adding an option.

Doesn't work too https://stackoverflow.com/questions/19325314/how-to-detect-cross-origin-cors-error-vs-other-types-of-errors-for-xmlhttpreq

Guess it's better to add the option + not recommending not to use a wildcard.

**Comment by electerious** [comment]
I've updated the docs and merged the re-added `ignoreOwnVisits` option. The develop branch now contains this changes. Will release it after some testing.
