### ISSUE TITLE
Vercel Deployment Error

### ISSUE THREAD

**Issue by AkashRajpurohit** [electerious/Ackee#221]
**🐞 Describe the bug**

The deployment failed for ackee on vercel.

**📚 To Reproduce**

Click the deploy with vercel button in the readme and follow the steps, add env variables and start the first deployment

**💡 Expected behavior**

Should deploy

**🖼️ Screenshots**

Build logs where it fails
```

Running "yarn run build"
--
10:09:32 | yarn install v1.22.4
10:09:32 | yarn run v1.22.4
10:09:33 | $ node build.js
10:09:33 | [1/5] Validating package.json...
10:09:33 | [2/5] Resolving packages...
10:09:33 | [Ackee] › …  awaiting  Building and writing 'dist/index.html'
10:09:33 | [Ackee] › ✔  success   Finished building 'dist/index.html'
10:09:33 | Done in 0.25s.
10:09:33 | Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings. Learn More: https://vercel.link/missing-public-directory
10:09:33 | success Already up-to-date.
10:09:33 | Done in 0.80s.
```

**⚙️ Environment**
 - Installation: [Vercel]
 - Ackee version: [latest]

**Comment by electerious** [comment]
> Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings. Learn More: https://vercel.link/missing-public-directory

It sounds like your Vercel installation wants to use the `public` directory, but it should use the `dist` folder instead. Please ensure that you're setting the correct output directory during the installation: https://github.com/electerious/Ackee/blob/master/docs/Get%20started.md#2-configure-ackee-1

I hope that helps! :)

**Comment by AkashRajpurohit** [comment]
It worked, thanks :)
