### ISSUE TITLE
Small typo in docs for Events

### ISSUE THREAD

**Issue by oakify** [electerious/Ackee#222]
**🐞 Describe the bug**

In the [Events page](https://github.com/electerious/Ackee/blob/master/docs/Events.md) there seems to be a small typo, seems worth changing but probably not making a PR for:
"List with average values: Shows the aggregated data as a list. Each entry includes the **total sum** of values. Perfect when an event contains different actions (e.g. tracking choices)."

**💡 Expected behavior**

Should be "the avarage value" instead of the total sum of values.

**Comment by electerious** [comment]
Fix on the develop branch. Thanks for letting me know!
