### ISSUE TITLE
Support Second Factor Authentication

### ISSUE THREAD

**Issue by BrookeDot** [electerious/Ackee#224]
**🐣 Is your feature request related to a problem? Please describe.**

While Ackee is a very basic application, the increased need for additional security is becoming increasingly necessary. I'm opening this to track the desire to add 2FA to Ackee and possible methods and alternative solutions.

**💡 Describe the solution you'd like**

On a daily bases in use TOTP (like Authy/Google Authenticator) authentication. These tend to be more secure than SMS authentication, and implementation would be quicker as an SMS provider would not be required. The other method I use is a hardware key (OTP Key like YubiKey). 

I would like to see either (or both) of those 2FA methods implemented. 

**❓ Describe alternatives you've considered**

Adding Basic Authentication at the server level is always an option. While doing so works, the basic auth password doesn't change like it would when using TOTP or a OTP key. 

Another alternative would be to limit the instance by IP again at the server/NGINX level.

**Comment by electerious** [comment]
I've never implemented a 2FA for a self-hosted application. I'm therefore not sure how complicated it is and if it's in the scope of a lightweight analytics tool.

I will close the issue, because I'm personally not interested to add this feature, but I'm open for suggestions or a discussion. A PR is also welcome, but the implementation should be discussed first.

**Comment by ViViDboarder** [comment]
One simple option here could be to support Proxy Auth and read the authenticated user from an `X-WebAuth-User` header. This would allow someone to have their proxy manage authentication with a provider that supports 2FA, for example: Traefik + Authelia.

**Comment by ViViDboarder** [comment]
Oh, also, if this is something you'd accept a patch for, I'd like to dig in a bit more but I haven't yet found where auth happens as I'm still familiarizing myself with NodeJS.

**Comment by electerious** [comment]
Not sure what it means for Ackee, but it sounds like a simple solution. A patch is welcome when there aren't too many changes for Ackee.
