### ISSUE TITLE
Geolocation Reup

### ISSUE THREAD

**Issue by vin-ni** [electerious/Ackee#229]
I'm aware this is currently not planned to release, but I personally would really really be happy about that feature. It's actually the only thing that prevents me from switching completely to Ackee. 

Maybe there is still a way of implementing it? 

Thank you!

**Comment by electerious** [comment]
The main issue with geolocations is that adding them usually requires a mix of license agreements, API keys and regular updates as discussed in https://github.com/electerious/Ackee/pull/105.

I'm open for ideas about how we could implement such a feature, but I will close the issue, because it's nothing I'm planning to add. PRs are welcome when we can find a solution that is optional and easy to maintain.

**Comment by BetaHuhn** [comment]
I recently looked into this again. As @electerious already mentioned, using a geolocation service/database is not very practical for a project like Ackee, but I found a few ways we could implement this feature in Ackee.

### Whois

We could use the `whois` service which lets you get all sorts of data about an IP address, including the country.

I tested the accuracy of whois against a few external geolocation APIs using a few hundred IP addresses. In my tests, the country in the whois record matches the one returned by the other geolocation services most of the time. When it didn't, the geolocation services also didn't agree on a country. 

One thing to note here, a large majority of the IP addresses I used where not "normal" residential IPs and instead datacenters or something similar, so in a real-world scenario whois is probably less accurate.

`whois` is already installed on almost any OS, but you could also query [ARIN's Whois-RWS API](https://www.arin.net/resources/registry/whois/rws/api/) directly. As `whois` is public and used for a variety of different use cases, this approach would not require any API keys or regular updates/local databases. After looking at [ARIN's TOS](https://www.arin.net/resources/registry/whois/tou/) I am not quite sure if our use case is allowed. I don't think Ackee would have a big Impact on their end and a lot of other tools/services use whois in a similar way.

It definitely is not as accurate as using a external geolocation service, but I think it might be a good compromise.

### Timezone

Another, albeit more complicated solution would be to use the users time zone to guess the country. Using the `Intl.DateTimeFormat()` API you could get the users time zone and then use the [IANA time zone DB](https://www.iana.org/time-zones) to cross reference the country. 

I created a NPM package to test this called [tzc](https://github.com/BetaHuhn/tzc). It definitely takes more work and we would have to deal with updates to the IANA database (for [tzc](https://github.com/BetaHuhn/tzc) I am using GitHub Actions to do this [automatically](https://github.com/BetaHuhn/tzc/blob/master/.github/workflows/update-time-zones.yml)).

Some users devices may use a different time zone than they are actually in, but geolocation using an IP address has similar inaccuracies with the rise in VPNs. 

If a users time zone doesn't include their country, we could simply use the region, which would still be better than nothing. E.g if a users time zone is `Europe/Berlin` we use `Germany` as the country and if it is only `CET` we use `Europe`.

### Cloudflare

This might not be a viable solution for a self-hosted service like Ackee, but I wanted to mention it anyway. Myself and probably a lot of Ackee users already use Cloudflare in front of Ackee to protect it from attacks as well as use their CDN to cache the ackee-tracker script. Cloudflare by default attaches the requests origin country in the `cf-ipcountry` header (more info [here](https://support.cloudflare.com/hc/en-us/articles/200168236-Configuring-Cloudflare-IP-Geolocation)). Ackee could check if this header is set and use the value as the users country.

I think it might be worth to take a closer look at each of the mentioned approaches, as more and more people seem to want the feature.

@electerious Let me know what you think and if theirs anything I missed or I may need to dig deeper on.

**Comment by CarlSinclair** [comment]
@BetaHuhn fantastic work! I and I'm sure many others would be very interested in a whois-based implementation or even a Cloudflare one. Sadly it is my impression that Ackee will never officially support such a thing, but that doesn't mean it can't be made available as an optional PR for those who decide the compromise is worth it for their use case.

Unfortunately, the codebase has changed significantly since the PR making it challenging to integrate today.
