### ISSUE TITLE
Netlify deploy succeeded but no data reported

### ISSUE THREAD

**Issue by Siddhant-k** [electerious/Ackee#230]
Hello!

I had a previous instance of Ackee working locally on macOS. I am trying to transition to Netlify and MongoDB Atlas to go serverless and I am having some issues. I deployed to Netlify using the button in the docs, and:

1. Along-with username and password, I also filled out the Mongo dB URI and most importantly, also filled the ACKEE_ALLOW_ORIGIN to my domain name.
2. I then added a domain in Ackee settings, and placed the script generated in the body of my website.

Ackee runs well, but I don't see any data reported back in the graphs.

Here are the debugging steps I have tried:
1. On my website, if I look at the source, I can access the tracker.js script hosted at Netlify
2. On my Mongo dB Collections view, I can see that Ackee has access to the dB and is actively doing R/W.

What else can I do to debug about Ackee-tracker not reporting back to Ackee?

Thanks so much!

**Comment by mathe42** [comment]
You can look at the Network tab in devtools.

**Comment by Siddhant-k** [comment]
Thanks, I do see an 8kb payload transferred in 371ms, type js to the correct Netlify site. I also see a failed payload of type "xhr" -- not sure what's that. It is just marked in red and says "--" for size. Anything else that I can look at?

**Comment by mathe42** [comment]
When you use chrome / MS Edge / Opera in the networktab you should see something like:
![image](https://user-images.githubusercontent.com/24830662/108548316-f64c2b00-72eb-11eb-9537-c9761d2eb5cb.png)

So 1 Preflight and a Request. If you click on the non preflight Request you can see all headers, data,... send to ackee. 

Under "General" you should see something like
![image](https://user-images.githubusercontent.com/24830662/108548566-4d520000-72ec-11eb-8585-706897fe3765.png)


> Just for your information what a preflight request is. The preflight request "asks" the server is it ok to send you a Request with this method. This happens when you do cross origin requests. And are a good thing but you have to set them up correct.

**Comment by mathe42** [comment]
Just one extra thing you can enable the console to show request debug infos:
![image](https://user-images.githubusercontent.com/24830662/108549308-437ccc80-72ed-11eb-96dd-0f910d92b214.png)

Enable "Log XMLHttpRequest".

**Comment by Siddhant-k** [comment]
Thanks for guiding me, I see interesting things happening. I see two requests to the api, one of which passes, one which fails:
<img width="825" alt="Screen Shot 2021-02-19 at 2 09 41 PM" src="https://user-images.githubusercontent.com/48394100/108552531-71e3b300-72bf-11eb-959b-7715553cf0a6.png">

The, the call that passes:
<img width="825" alt="Screen Shot 2021-02-19 at 2 09 37 PM" src="https://user-images.githubusercontent.com/48394100/108552553-7b6d1b00-72bf-11eb-8e0a-8077221c6965.png">

Next, I checked the Console, and it has the following error message:
```
Access to XMLHttpRequest at 'https://lucid-tereshkova-54773b.netlify.app/api' from origin 'https://siddhantkhera.ca' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
````

I see that setting the [Access-Control-Allow-Credentials](https://github.com/electerious/Ackee/blob/v3.0.0/docs/CORS%20headers.md#credentials) to _true_ was a relevant change released in v3. Did I miss adding it somewhere while setting up Ackee in Netlify? Should I add this in my HTML headers (not sure if that's how it works)?

**Comment by electerious** [comment]
That's a known bug, but there was something wrong with Vercel the last time I've tried to test it. That's why it's still not fixed in Ackee :-/ https://github.com/electerious/Ackee/issues/223

**Comment by mathe42** [comment]
Just thought the same. @Siddhant-k you could disable the chredentials in ackee-tracker.

**Comment by Siddhant-k** [comment]
Oh okay fantastic. I did try adding the following to my netlify.toml of my website:
```Access-Control-Allow-Credentials = "true"```
and it didn't help. I'll disable the credentials in ackee-tracker and report back.

**Comment by Siddhant-k** [comment]
Setting ```ignoreLOwnVisits: false``` fixes the issue. How can I also include the detailed attribute with this one? This is what I have currently and detailed stats are not working:
```
<script async src="https://lucid-tereshkova-54773b.netlify.app/tracker.js" data-ackee-server="https://lucid-tereshkova-54773b.netlify.app" data-ackee-domain-id="92b853c8-690f-48aa-9e26-f009818b3d72" data-ackee-opts='{ "ignoreOwnVisits": false, “detailed”: true}’></script>
```

And one final thing, I don't know if it has come up for others (I couldn't find any issues related to it, Netlify fails to push to my repo after the initial build is complete:
```Error pushing to remote repository at git@github.com:Siddhant-k/Ackee```

So even though the initial build succeeds, my repo is empty. I fixed that by manually fetching the upstream and pushing the commit to master on my repo (just like I would update my repo with the latest release). I''m thinking it might have been something with my config, but just wanted to put it out there if someone else has similar issues.

**Comment by electerious** [comment]
The CORS bug has been fixed. Might be worth to give it another try. Disabling `ignoreLOwnVisits: false` isn't required anymore (for Platforms-As-A-Service deployments).

@Siddhant-k Your configuration looks fine. Ackee should show detailed data. Are the detailed stats still empty?

**Comment by Siddhant-k** [comment]
Yep, just pulled the latest commit and it if fixed. Thank you for that!

I’m not sure why that didn’t work, and detailed stats were empty. I’ve removed ignoreOwnVisits attribute now, leaving only the detailed attribute and it works now. Thanks for helping me out!!
