### ISSUE TITLE
Per page statistics

### ISSUE THREAD

**Issue by ManUtopiK** [electerious/Ackee#234]
**🐣 Is your feature request related to a problem? Please describe.**

I wonder if we can fetch per page statistics with the graphql API? I explored a lot but don't found a way to do that.

**💡 Describe the solution you'd like**

Exemple to fetch total view, extend type `DomainStatistics` with `View()` query like this:
```gql
view(
    id: URL!
    interval: Interval!
    limit: Int = 14
): [View!]
```

**Comment by electerious** [comment]
Not sure if that's what you're looking for, but there's a pages field you can query:

pages(sorting: Sorting!
range: Range = LAST_7_DAYS
limit: Int = 30
): [Page!]

**Comment by ManUtopiK** [comment]
Thanks for your response.
No. It's not that I want. Sorry, maybe I misspoke.
I would like to get view statistics **per page**. As we can get with `view` but for one page:
```gql
query stats {
    domain(id: "d007c978-97a6-4bb7-b2f8-43a635c317df") {
       statistics {
	   views(
                interval: DAILY
                type: TOTAL
            ) {
                id
                count
            }
        }
    }
}
```
The result is something like:
```gql
"data": {
    "domain": {
      "statistics": {
        "views": [
          {
            "id": "2021-03-05T21:39:35.992Z",
            "count": 243
          },
          {
            "id": "2021-03-04T21:39:35.992Z",
            "count": 193
          },
          {
            "id": "2021-03-03T21:39:35.992Z",
            "count": 288
          }
...
```
Note field `id` is strange for a date.
Anyway, those results are for the whole domain, not about one unique page.
It could be useful to obtain stats per page. Something like:
```gql
query stats {
    domain(id: "d007c978-97a6-4bb7-b2f8-43a635c317df") { // or just `domains {`
       statistics {
	   views(
                id: "https://mywebsite.org/theUrlOfThePageIWant"
                interval: DAILY
                type: TOTAL
            ) {
                id
                count
            }
        }
    }
}
```

**Comment by electerious** [comment]
Ahh I see. I like the idea, but I currently have no use-case in the UI for it. It's therefore nothing I'm planning to add.

**Comment by ManUtopiK** [comment]
I'm currently working on it here: https://github.com/ManUtopiK/Ackee/tree/viewsPerPage

**Comment by mab253** [comment]
I would also be very interested in views per page for older than 6 months - @ManUtopiK any luck here?!

(I'm hoping to be able to build a cumulative all-time count in the dashboard as well, for pages specifically)

**Comment by ManUtopiK** [comment]
Sorry. I had no help with this feature. I switched to https://github.com/umami-software/umami

**Comment by mab253** [comment]
I was able to adjust the range filters to show "Last 12 Months," "Last 7 Years" (and I believe you could go higher, essentially giving yourself an "All Time" statistic for page views)! 

For @ManUtopiK and anyone else looking: https://github.com/UnlockNYC/Ackee/commit/3a70457ed2595fe288f4698914f5d595d35a6598
