### ISSUE TITLE
Visitors not getting registered in Brave Browser: Client sending empty GUID as payload

### ISSUE THREAD

**Issue by CookedApps** [electerious/Ackee#236]
**🐞 Describe the bug**

Visitors using Brave Browser are not getting registered. I also tried disabling any blocking of trackers but no difference. I noticed that the network request to my Ackee instance are arriving, but the payload seems odd: The payload ID is always 888-... (See the screenshot below.) I also noticed that the subsequent periodic requests to Ackee are not happening.
Other browsers on my system don't show this behavior. The payload id is a random GUID (as I would expect) and the periodic requests are getting sent. Notice: "Use detailed statistics" is set to true.

**📚 To Reproduce**

Use the described environment and open the website.

**💡 Expected behavior**

The GUID should get correctly initialized and therefore the client getting registered. Also the periodic requests to Ackee should happen.

**🖼️ Screenshots**
![Screenshot](https://i.ibb.co/ssx843T/Screenshot-from-2021-03-05-10-43-27.png)

**⚙️ Environment**

 - Installation: Docker/Docker-Compose
 - Ackee version: 3.0.5
 - use-ackee React version: 3.0.0
 - Browser: Brave Version 1.21.73 Chromium: 89.0.4389.72 (Official Build) (64-bit)
 - OS: Linux Mint 20.1 Cinnamon

**Comment by electerious** [comment]
Ackee ignores your own visits. This should be the case when you've logged into Ackee using the same browser. There should also be a console warning in that case.

Can you give it a try using the private mode of the browser?

**Comment by CookedApps** [comment]
Ah yes, you are right... I somehow didn't think about looking in the console. You can close this issue. Sorry for the inconvenience, and thank you for this awesome project!
