### ISSUE TITLE
Conversion Tracking

### ISSUE THREAD

**Issue by walski** [electerious/Ackee#237]
## Problem

Given Ackee comes with both, a way to track sources (`?source=XYZ`) as well as a way to track events, it would be great if there would be a way to track conversions based on the source.

I understand that this would only within the TTL of the ClientID, but for many websites that might be good enough? At least better than nothing :)

## Ideal Solution

Ideally I could see on any event, a breakdown of all (initial?) sources of the ClientIDs that have tracked that event.

This would work for any of the temporal aggregation levels (daily/monthly/yearly).

## Alternative Solutions

If possible I would be happy to build that on top of the existing API but I don't see a way to do that.

I'd be happy to help out building this feature but wanted to check first if this is something that would even be considered as a PR, before giving it a shot :)

Thanks for your great work!

**Comment by electerious** [comment]
Thanks for the suggestion, but it's nothing I'm currently planning to add. Ideas or suggestions however are still welcome.
