### ISSUE TITLE
404 Error on sign-in

### ISSUE THREAD

**Issue by avsteele** [electerious/Ackee#238]
**🐞 Describe the bug**

When I try use the `sign in` button on the ackee login page I get the following error (my server's domain is replaced with `example.com` in the info below)

```html
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

Error: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

    at Md (https://example.com/ackee/index.js:83:13349)
    at async https://example.com/ackee/index.js:83:13926
```

This error occurs up no what username/password is typed. 

**📚 To Reproduce**

I setup and installed using the instructions at:
https://docs.ackee.electerious.com/#/docs/Get%20started#without-docker

I have a reverse proxy that forwards requests from example.com/ackee/ to the ackee app running on localhost:3000. 

I suspect this might be a problem with my reverse proxy. But as Ackee suggested checking here I though I'd try that to get an opinion.

**💡 Expected behavior**

Login to dashboard or error on wrong username/password

**🖼️ Screenshots**

![image](https://user-images.githubusercontent.com/25284525/111075657-6ef37100-84bf-11eb-8011-49617b0c55ed.png)

**⚙️ Environment**
 - Installation: Manually
 - Ackee version: 3.0.5

**📋 Additional context**

MongoDB works OK, as i can access its console.

I did receive a warning when using yarn to update dependencies. 
> yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "graphql-tools > @graphql-tools/links@7.0.4" has unmet peer dependency "@apollo/client@~3.2.5 || ~3.3.0".
[5/5] Building fresh packages...
Done in 94.91s.

on starting the app with `yarn start` I do get another warning:
>  [Ackee] › …  awaiting  Building and writing 'dist/index.html'
 [Ackee] › ✔  success   Finished building 'dist/index.html' 
 \> ackee@3.0.5 server
 \> node src/index.js
[Ackee] › …  awaiting  Connecting to mongodb://localhost:27017/ackee
(node:1977) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1977) DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.
[Ackee] › ✔  success   Connected to mongodb://localhost:27017/ackee
[Ackee] › ▶  start     Starting the server
[Ackee] › …  watching  Listening on http://localhost:3000

nginx's logs report the following (1st line on acess, second line when hitting `sign in`
> 108.31.153.3 - - [14/Mar/2021:16:00:17 +0000] "GET /ackee/favicon.ico HTTP/1.1" 200 52852 "https://example.com/ackee/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.86 Safari/537.36"
108.31.153.3 - - [14/Mar/2021:16:01:25 +0000] "POST /api HTTP/1.1" 404 209 "https://example.com/ackee/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.86 Safari/537.36"

Thanks a lot for any suggestions!

**Comment by electerious** [comment]
My guess is that Ackee tries to call the API via `example.com/api/` instead of using `example.com/ackee/api`. I've only ever used it via a sub-domain.
