### ISSUE TITLE
[Docker] Multiple User Support

### ISSUE THREAD

**Issue by kaaax0815** [electerious/Ackee#239]
**💡 Describe the solution you'd like**
Multiple Enviroment Variables for Multiple Users with their own Passwords

**📋 Additional context**

a login with "user""password" and "user1""password1"

**Comment by mathe42** [comment]
dublicate of #187

This will not happen :(

**Comment by BetaHuhn** [comment]
Also, depending on the actual use case, #225 maybe sufficient.

**Comment by kaaax0815** [comment]
I dont want Permissions only different Users so i dont need to share my password

**Comment by mathe42** [comment]
Ah I think I can create this. Should be a (simple) change to https://github.com/electerious/Ackee/blob/master/src/resolvers/tokens.js

If @electerious is open for a PR I will work on this in the next days.

**Comment by electerious** [comment]
@mathe42 It shouldn't be hard to add, but I also don't think that it's a benefit for most users. I therefore don't have any plans to add support for it.
