### ISSUE TITLE
Create a page with instance informations

### ISSUE THREAD

**Issue by jbleuzen** [electerious/Ackee#24]
I have installed Ackee on several server and I'm facing a "maybe only for me" problem. In fact, I want to know which version is running when I'm browsing Ackee so that I can know if I have the latest available version (eventhough development is not very active)...

This is more an enhancement that a bug. I would love to code this feature, I wish I will...

**Comment by electerious** [comment]
Ackee shows the current version in the login, but I agree that it would be a nice addition to show when an update is available.

**Comment by electerious** [comment]
The new server allows to track and separate data by domain. It's planned that the new UI has the same functionality.
