### ISSUE TITLE
Toggleable authentication provider

### ISSUE THREAD

**Issue by PierreSchwang** [electerious/Ackee#240]
**🐣 Is your feature request related to a problem? Please describe.**

It would be great if the authentication for the dashboard could be disabled to use other (centralized) authentication providers, like authelia or login using x.509 certificates.

**💡 Describe the solution you'd like**

E.g. an environment variable which disables the internal authentication provider. Alternative, keeping the user and password empty.

**Comment by electerious** [comment]
Makes sense. Shouldn't be hard to implement. PR welcome.

I guess that `src/utils/isAuthenticated.js` needs to be modified. It shouldn't require a token when the username and password is unspecified. Creating a token however should still throw an error when there's no username and password in the environment.

Bonus: Remove "Sign Out" from the Settings page when in a token-less environment. There's a `window.env` in `src/utils/layout.js` which could contain a `requireCredentials` option.

**Comment by PierreSchwang** [comment]
I'll try to do that, just had some issues to run ackee on windows ^^'

**Comment by electerious** [comment]
I currently don't have any plans to add support for custom authentication provides, but a lightweight solution or suggestions are still welcome.
