### ISSUE TITLE
Custom metrics

### ISSUE THREAD

**Issue by robertsLando** [electerious/Ackee#241]
Hi everyone! Thanks for the amazing project. I would like to know if Ackee can or will provide a way to add some custom metrics and create custom dashboards

**Comment by electerious** [comment]
Hey @robertsLando, glad you like Ackee! Do you have an example for "custom metrics"? There's an Events API that accepts various data. It might be what you're looking for.

**Comment by electerious** [comment]
(Closing the issue because of the lack of feedback)
