### ISSUE TITLE
Docs improvement: Fix hyperlinks on privacy policy reference HTML

### ISSUE THREAD

**Issue by ChrisRomp** [electerious/Ackee#257]
The sample HTML on the [Privacy Policy](https://docs.ackee.electerious.com/#/docs/Privacy%20Policy) page uses `target="_blank"` and should therefore include `rel="noopener noreferrer"` inside of the `<a>` element as a best practice to prevent "[reverse tabnapping](https://owasp.org/www-community/attacks/Reverse_Tabnabbing)" ([ref](https://stackoverflow.com/questions/50709625/link-with-target-blank-and-rel-noopener-noreferrer-still-vulnerable)).

E.g.: `<a href="https://ackee.electerious.com" target="_blank" rel="noopener noreferrer">Ackee</a>.`

**Comment by electerious** [comment]
Merged 😊 Thanks for the PR!
