### ISSUE TITLE
Cache preflight responses (Access-Control-Max-Age)

### ISSUE THREAD

**Issue by ThomasOrlita** [electerious/Ackee#261]
**🐣 Is your feature request related to a problem? Please describe.**

Every time a CORS request to Ackee is sent, it is preceded by a preflight OPTIONS request which allows the website to send the request. However, since no `Access-Control-Max-Age` header is sent, the preflight request is sent every time.

**💡 Describe the solution you'd like**

Send `Access-Control-Max-Age` alongside the [`Access-Control-Allow-{Origin,Methods,Headers,Credentials}` headers](https://github.com/electerious/Ackee/blob/264df73a506df5f0f01a7b1eddaea17b7d17cd11/src/server.js#L86). This means the OPTIONS header will have to be sent only once per site and then the browser won't send the preflight request again until the cache expires.

**Comment by electerious** [comment]
I've implemented it, but reverted it for now. I'm not sure how the caching works when allowing multiple origins. Both Ackee and the recommended nginx config are dynamically changing the origin based on the request. Caching the origin would be problematic in that case.

**Comment by mathe42** [comment]
I looked at the spec:

`Access-Control-Max-Age`
Indicates the number of seconds (5 by default) the information provided by the `Access-Control-Allow-Methods` and `Access-Control-Allow-Headers` headers can be cached.


So Origin is not cached. 


For spec see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age


Note that
Firefox caps this at 24 hours (86400 seconds).
Chromium (prior to v76) caps at 10 minutes (600 seconds).
Chromium (starting in v76) caps at 2 hours (7200 seconds).

(see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age#directives)

**Comment by mathe42** [comment]
As I understand the result preflight request is cached. So the browser has for each origin a list of cached preflight requests so the cached data don't need to contain information about the allow-origin header as only successfull preflights are cached.

**Comment by ThomasOrlita** [comment]
I've been sending the preflight cache header from 2b170a44d3de3dbf46554767139387443776a13d for half a year now and it works without any issues.

**Comment by electerious** [comment]
@ThomasOrlita Thanks for letting me know. I've merged the branch. It will be a part of the next release :)
