### ISSUE TITLE
Serverless mode using dgraph

### ISSUE THREAD

**Issue by gotjoshua** [electerious/Ackee#262]
**💡 Describe the solution you'd like**

I'd love a privacy sensitive analytics solution that is fully serverless. 

**📋 Additional context**

[dGraph](https://github.com/dgraph-io) offers a graph based db solution with [serverless graphQL](https://cloud.dgraph.io/) endpoints. 
I believe Ackee could be forked or rather extended to offer a serverless dgraph based option.\
phase 1 could be self-hosted dgraph instead of mongo  
phase 2 could be serverless style  

Do you have a discord or telegram dev group where we could discuss such a possibility?

**Comment by gotjoshua** [comment]
whoa, just discovered there already is a serverless mode!! 
 https://github.com/electerious/Ackee/blob/master/src/serverless.js

**Comment by electerious** [comment]
Yep, there's already a serverless mode in Ackee that works with Vercel, Netlify and co. I hope that helps, but I don't plan to switch to a DB other than MongoDB. It does a good job for what Ackee needs :)
