### ISSUE TITLE
[Feature request] Display full text on hover

### ISSUE THREAD

**Issue by marchellodev** [electerious/Ackee#266]
**🐣 Is your feature request related to a problem? Please describe.**

Right now when the text is too long, it will just get cropped, with no way to see the whole string (besides inspecting the element).

![image](https://user-images.githubusercontent.com/61112084/122124280-ba5b4980-ce37-11eb-9de6-cadb03ec6464.png)

**💡 Describe the solution you'd like**

Displaying the full string when hovering mouse over the cropped text

**❓ Describe alternatives you've considered**

Opening the full text in a cute dialog might also be an option :)

**Comment by electerious** [comment]
Implemented. Will be a part of the next release :)

**Comment by marchellodev** [comment]
I do not think this issue is fixed in 3.1.1. I hover over the trimmed text but noting happens

![image](https://user-images.githubusercontent.com/61112084/123552171-9542d100-d77d-11eb-8ab4-2c60842e473a.png)

**Comment by electerious** [comment]
It should show up after a short delay
![Screenshot 2021-07-18 at 13 26 26](https://user-images.githubusercontent.com/499088/126065307-034da04d-bca4-4020-b465-c5bbd3192675.png)

**Comment by marchellodev** [comment]
It does not work :))))

I have now tried firefox and brave (based on chromium)
