### ISSUE TITLE
Impossible to restart with Supervisor

### ISSUE THREAD

**Issue by postblue** [electerious/Ackee#27]
To keep Ackee as a service on my server, I use Supervisor. Here's the configuration file:

```
[program:ackee]
command = npm start
directory = /path/to/ackee
user = ackee
autostart = true
autorestart = true
startsecs = 60
stdout_logfile = /var/log/supervisor/ackee.log
stderr_logfile = /var/log/supervisor/ackee_err.log
```

But, if I stop the service, it keeps running in background, thus I have to kill the node command running. Is it possible to run Ackee with a node or coffee command, like with most of the node webapplications ?

```
[program:etherpad]
command = node /path/to/etherpad/src/node/server.js
directory = /path/to/etherpad
user = etherpad
autostart = true
autorestart = true
startsecs = 60
startretries = 10
stdout_logfile = /var/log/supervisor/etherpad.log
stderr_logfile = /var/log/supervisor/etherpad_err.log
```

I hope this is possible.
Thank you for ackee!

**Comment by jbleuzen** [comment]
I remember I had issues trying to setup my server with initd. You could try to launch ackee with the coffee command without using ```npm start```

**Comment by electerious** [comment]
Starting Ackee using `coffee ackee.coffee` won't work, as Ackee needs values from the `package.json`. Has something to do with the [config settings](https://docs.npmjs.com/cli/config). Don't ask me for details, I don't know how this works anymore.

BTW: I'm currently [rewriting Ackee](https://github.com/electerious/Ackee/tree/v2) from the ground-up. The new architecture should make things easier.

**Comment by postblue** [comment]
@jbleuzen, I tried with the coffee command, but as @electerious points out, it isn't working.
@electerious Then maybe I'll wait for V2 to be functionnal and test it! (Or is it already?)

**Comment by electerious** [comment]
@postblue Will take a while. Still a lot to do…

**Comment by electerious** [comment]
*The old version has been deprecated.*

**Comment by postblue** [comment]
New version!? Yipeeeee, will try!

**Comment by electerious** [comment]
@postblue I finished the server and tracking-script. The new version has no UI at the moment, but I hope that I have the time to start working on it soon. The server now has a RESTful API and is fully documented. The script is installable via npm and bower, which makes it much easier to use. An UI will make the project complete :)
