### ISSUE TITLE
Create a Vultr & Linode one click deployment solution

### ISSUE THREAD

**Issue by sid-r-singh** [electerious/Ackee#274]
## 🚀 Feature request
**📋 Additional context**

Looks like there is not much support from DigitalOcean on creating a DigitalOcean one click deployment solution but the case with Vultr is different. They contact the developer back & coordinate with them to create Vultr one click deployment solution. Full details are available [here](https://www.vultr.com/marketplace/become-a-verified-vendor/#learn-more).

Same is the case with Linode as well. They also get back to the developer. Also they use StackScript for this, which looks like is just a collection of bash commands. More info [here](https://www.linode.com/marketplace/app-partners). Just for info. here is a [StackScript-Example.sh](https://github.com/linode/Marketplace-Apps/blob/master/StackScript-Example.sh) & more examples [here](https://github.com/linode/Marketplace-Apps).

**Comment by electerious** [comment]
The Get Started-Guide already covers a lot of services and I'm still open for more. PRs are welcome!
