### ISSUE TITLE
View Ackee Reports Without Logging In

### ISSUE THREAD

**Issue by Zozman** [electerious/Ackee#276]
**🐣 Is your feature request related to a problem? Please describe.**

For situations where you're running Ackee behind a reverse proxy and providing your own authentication layer there (such as nginx's auth_request module) it would be convenient to be able to disable having to provide a username and password.

**💡 Describe the solution you'd like**

This could be implemented by having an environmental variable that you could set that would either remove the authentication prompt completely when visiting the dashboard or remove it from reports and only require authentication when visiting a sensitive page such as Settings.

**❓ Describe alternatives you've considered**

It would be nice to be able to pre-fill in the credentials like when you visit https://demo.ackee.electerious.com/ but I have not seen anything in the documentation saying how to do this.

**Comment by sid-r-singh** [comment]
This is very much a highly sought-after feature. I would love to have the dashboard publicly available. As you said there can be a toggle switch which modifies the environment variable to make the dashboard public or private.

**Comment by Zozman** [comment]
I was thinking you could do something like https://github.com/Zozman/Ackee/commit/a3c96039e32e4e97a392ae428423a95d39f5fe60 where you could have a `ACKEE_ANONYMOUS` environmental variable that if set to `true` then the token would be auto-generated when the UI is opened instead of needing a username and password entered.

**Comment by electerious** [comment]
This feature isn't planned as it doesn't work with the way Ackee was built. 

> There was already a similar experiment, but we couldn't find a way to protect the UI while keeping the /api endpoint public. ackee-tracker can't track visits when the endpoint isn't public and a public endpoint without a password protection means that everyone can modify and see your data.

I'm however open for a data sharing option which could allow to share domain statistics via a link with a permanent token: https://github.com/electerious/Ackee/issues/225
