### ISSUE TITLE
Refusing To Deploy - Railway

### ISSUE THREAD

**Issue by JaiRelan** [electerious/Ackee#280]
**🐞 Describe the bug**
Used the one-click deployment to railway. Set the username and password as expected but getting the following error while deploying.

```
18: Pulling from heroku/buildpacks
Digest: sha256:122bb39f566a1943bf5558b4b792fc040480204e5ce3e455a32b830fbe0e15d1
Status: Image is up to date for heroku/buildpacks:18
18: Pulling from heroku/pack
Digest: sha256:05192dbbef44c70d9a1d93a49ce05182b90266fb7c5b5ac7f863a24ac27597d5
Status: Image is up to date for heroku/pack:18
===> DETECTING
======== Output: heroku/ruby@0.0.1 ========
no
err:  heroku/ruby@0.0.1 (1)
ERROR: No buildpack groups passed detection.
ERROR: failed to detect: buildpack(s) failed with err
ERROR: failed to build: executing lifecycle: failed with status code: 101
```

**📚 To Reproduce**

Click the deploy button in the documentation, enter your username and password. This error message will come on the right-hand side. 

**💡 Expected behavior**

It should deploy.

**🖼️ Screenshots**
![CleanShot 2021-08-01 at 12 48 36](https://user-images.githubusercontent.com/40684950/127762707-7f323aa9-abad-401e-9055-c36d14affba5.png)

**⚙️ Environment**
 - Installation: Railway
 - Ackee version: [e.g. v2.1.0]

**Comment by electerious** [comment]
@FarazPatankar Do you have any idea? You've once added Railway to the guide. I'm personally not using Railway so I can't offer any help.

**Comment by FarazPatankar** [comment]
Thanks for the tag, @electerious. @JaiRelan did you use the Railway starter for this? You can deploy Ackee directly on Railway from [here](https://railway.app/new/starters/ackee)!

**Comment by JaiRelan** [comment]
@FarazPatankar Hmm, that's odd. The link which you gave in the comment seems to do the trick. However, when I used the link mentioned [here](https://github.com/electerious/Ackee/blob/master/docs/Get%20started.md#with-railway) 2 days ago, it gave me the error which I screenshotted above.

**Comment by FarazPatankar** [comment]
Whoops, we've moved the starter since then. Any chance you could create a PR to update that link? :)

**Comment by JaiRelan** [comment]
This is probably like my first __serious__ PR so I'm super pumped. Done and dusted! Thanks a ton again

**Comment by FarazPatankar** [comment]
@electerious I think we can close this now?
