### ISSUE TITLE
Request events for domains

### ISSUE THREAD

**Issue by jjzcru** [electerious/Ackee#282]
**🐣 Is your feature request related to a problem? Please describe.**

I'm trying to track the events from multiple domains but i would like to attack the events to an specific domain instead of merging all events together.

**💡 Describe the solution you'd like**

Being able to send and fetch events for each domain.

**📋 Additional context**

I'm supporting multitenancy on my app and i would like to group events and actions for each tenant

**Comment by electerious** [comment]
Hey @jjzcru, thanks for the suggestion. Events are currently decoupled from domains and there's no relation between them. I don't think this will change anytime soon as it would require several changes. I guess that creating multiple events is the only solution.
