### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by gempain** [electerious/Ackee#283]
**🐣 Is your feature request related to a problem? Please describe.**

I'm trying to deploy Ackee entirely in the cloud using free options out there. While I can host Ackee on Heroku, I still need a Mongo database somewhere.

**💡 Describe the solution you'd like**

While I understand from [previous issues](https://github.com/electerious/Ackee/issues/118) that you're not planning to switch to this, I would like to suggest using TypeORM, which would both allow anyone to chose their favorite storage. AFAIK, switching to TypeORM would not be very hard.

**❓ Describe alternatives you've considered**

Using Mongo Atlas, but they don't offer a free tier anymore.

**📋 Additional context**

I could find time to help on this, but I'm not starting a PR without having discussed this with you ahead of time.

And as always, many thanks for this great project which I try to promote when the opportunity comes.

**Comment by electerious** [comment]
Thanks for the suggestion, but it's currently not planned to move away from MongoDB or to support different databases.
