### ISSUE TITLE
Add arm64 support (and probably arm32v6, arm32v7 too)

### ISSUE THREAD

**Issue by lohmatij** [electerious/Ackee#286]
**I tried to run Ackee on Oracle Ampere (ARM) instance and it failed.**

ARM servers are becoming more and more popular. They are cheap compared to amd64 architecture. For example Oracle gives 4 CPU 24GB ARM instance for free (forever). That's much better than 1 CPU 0.5GB AMD64 instance they also offer for free (forever).

**Please make an ARM Docker image**

Arm support for you docker image will be perfect. I made it myself in 3 minutes: just changed "mhart/alpine-node:14" in your Dockerfile to official "node:14-alpine" and it compiled just perfectly. You can check my ackee image at dockerhub at "lohmatij/ackee:alpine", but of course it would be better if you make an official image yourself.

**📋 Additional context**

Official Docker Node.js image supports these architectures: amd64, arm/v6, arm/v7, arm64/v8, ppc64le, s390x

**Comment by electerious** [comment]
Ackee v3.2.0 is out and uses the official Docker Node.js image 😊 Thanks for the suggestion!
