### ISSUE TITLE
Unable to login Ackee deployed to Netlify

### ISSUE THREAD

**Issue by OPerel** [electerious/Ackee#289]
**🐞 Describe the bug**

I got everything working locally, and I deployed successfully to Netlify.
But when trying to login using the credentials defined in the env variables I get the following error:
```
Response not successful: Received status code 502
```

**📚 To Reproduce**
I just deployed to Netlify using the button in the docs...

**💡 Expected behavior**

I should be able to login and see my dashboard.

**🖼️ Screenshots**
Ackee login screen:
![image](https://user-images.githubusercontent.com/42510547/132823042-de12e088-e98e-4ff5-b0b8-9283237f6219.png)

This is what I'm seeing in the Chrome dev tools:
![image](https://user-images.githubusercontent.com/42510547/132823195-756bc8f5-2f9e-4c28-a622-b8ff239a306c.png)

And this is what I'm seeing in the Netlify functions olg:
![image](https://user-images.githubusercontent.com/42510547/132823270-009c3c58-aba4-4b08-8a45-7791abd1087b.png)

**⚙️ Environment**
 - Installation: Netlify
 - Ackee version: `v3.1.1`

**📋 Additional context**

Please let me know if I can provide any more info on this issue

Thanks 🙏

**Comment by carvalholeo** [comment]
Hello, how are you?

At MongoDB Atlas, did you set up your user to be access from all internet (on sidebar, at Network configurations) and your user to have permission to read and write any database?

I did the same problem, because I've configured ackee database user to be an administrator, so they can't be able to write anything. Solved when I gave that permissions.

**Comment by OPerel** [comment]
Thanks @carvalholeo 
My DB user was configured as admin. I thought admin should have read and write privileges....
Any way it's working now!
🙏

**Comment by carvalholeo** [comment]
YESSS, I thought it too in my case.

I'm happy that you fix your problem. Happy coding and happy data!

**Comment by BasJan81** [comment]
I've used the Deploy to Netlify button and receive the same 502 error.

Could someone please explain how to find the correct  **ACKEE_MONGODB**   URL info?

I created a database, user and password but I can't find the database URL.

**Comment by electerious** [comment]
> I created a database, user and password but I can't find the database URL.

That depends on the platform you use. The URL usually looks like this: https://docs.mongodb.com/manual/reference/connection-string/
