### ISSUE TITLE
Uncaught SyntaxError: JSON.parse errors

### ISSUE THREAD

**Issue by Brodie-Hamilton** [electerious/Ackee#297]
**🐞 Describe the bug**

#### BUG 1

After deploying a fresh instance of Ackee onto a Vercel instance, on login I get logged back out periodically with the following error:
> JSON.parse: unexpected character at line 1 column 1 of the JSON data up/</<@https://my-site-url/index.js:80:80220

#### BUG 2

Also when attempting to integrate the Ackee tracker into my Svelte-based site (via the embedded JS script method) I get the following error in my browser console when visiting my site:
>Uncaught SyntaxError: JSON.parse: expected double-quoted property name at line 1 column 29 of the JSON data

This appears to prevents the tracker from sending any tracking information to my Ackee server as I am getting no data even though I have explicitly disabled the prevention of tracking by setting the options to:
>'{ "ignoreLocalhost": false, ignoreOwnVisits: false }'

Confirmed both of the above behaviours in Firefox as well as Chrome.

**📚 To Reproduce**

1. Deploy a new instance via steps: https://github.com/electerious/Ackee/blob/master/docs/Get%20started.md#with-vercel
2. Once configured correctly, attempt to log in.
3. After login the page logs out periodically with the following error. Appears to only happen on the index page.

**🖼️ Screenshots**

<img width="431" alt="Screen Shot 2021-10-30 at 4 27 02 pm" src="https://user-images.githubusercontent.com/35979029/139522815-8d4f627c-a28b-42e9-b6c4-6779a8d6b62a.png">

**⚙️ Environment**
 - Installation: Vercel
 - Ackee version: 3.2.0

**Comment by benmneb** [comment]
Similar issue here, my login fails with `JSON.parse: unexpected character at line 1 column 1 of the JSON data`. It's also a fresh Vercel deployment on Ackee version 3.2.0.

<img width="412" alt="" src="https://user-images.githubusercontent.com/62878664/139804706-345149ac-7a63-4269-9b11-b30fc22da9c1.png">

**Comment by electerious** [comment]
It would be interesting to know what the server responds with. Could you take a look at the network inspector of the browser? It should contain a request to `/api` with a non JSON response.

Another helpful indicator is the serverless function log in Vercel. It should tell us more about the error.

**Comment by electerious** [comment]
Closing this issue, because I need the serverless function log.
