### ISSUE TITLE
ARM64 Docker Support (Also other arm architectures)

### ISSUE THREAD

**Issue by Divkix** [electerious/Ackee#298]
Hey

I tried ackee on Vercel and would like to host it on my own Cloud VM (using Oracle Free Cloud tier), but unfortunately the official Docker Image doesn't support ARM yet.

I read about about the same in #286 but still can't see the ARM tagged images for Ackee.

Would really appreciate if there would be an official ARM image for Ackee.

**Comment by electerious** [comment]
Hey @Divkix, thanks for letting me know. Is there anything I need to add to the Dockerfile to support ARM64 (and other architectures)?

**Comment by Divkix** [comment]
Hey @electerious, the Dockerfile seems fine, you'll need to use docker buildkit in order to build images for multiple architectures.

Can tou let me know how do tou build the images before pushing them to Docker Hub?

**Comment by electerious** [comment]
I've just publish a new develop tag to Docker with support for other platforms. Please let me know if everything works as expected so I can create a new release 😊

![Screenshot 2021-12-01 at 20 02 50](https://user-images.githubusercontent.com/499088/144297382-c46b581a-2b72-4fa3-b95d-d1066d272b8c.png)

**Comment by Divkix** [comment]
The release works great on `linux/arm64`, I haven't been able to try on `linux/arm/v7` because I don't have anything which runs on it, but I think that it should work.
Everything works as expected for arm64 :)

**Comment by electerious** [comment]
Perfect, thanks for letting me know! v3.3.0 is now live: https://github.com/electerious/Ackee/releases/tag/v3.3.0
