### ISSUE TITLE
MongoDB v5 compatibility

### ISSUE THREAD

**Issue by shaftoe** [electerious/Ackee#303]
**🐣 Is your feature request related to a problem? Please describe.**

Hello Ackee, I'm not sure how else to ask about this so I drop it here, hope it's fine. I've just received this from MongoDB Atlas and I'm wondering if it's going to affect my Ackee (Heroku) installation, that is, if there's anything I'll have to take care of or if the current latest of Ackee is already supporting v5:

> Your M0/M2/M5 Atlas cluster(s) will automatically be upgraded to MongoDB 5.0 in early February 2022.

Thanks!

**Comment by electerious** [comment]
MongoDB v5 is supported :) https://github.com/electerious/Ackee/pull/291

**Comment by shaftoe** [comment]
Awesome! thanks for the quick reply
