### ISSUE TITLE
Context creation failed: command find requires authentication

### ISSUE THREAD

**Issue by jaschaschmidt** [electerious/Ackee#308]
**🐞 Describe the bug**

Context creation failed: command find requires authentication.
This only happens when authentication is enabled on the MongoDB Server.

**📚 To Reproduce**

Enable authentication on the MongoDB Server v4.4.10 and try to connect to the database.

**💡 Expected behavior**

The connection should work when authentication is enabled.

**🖼️ Screenshots**

N/A

**⚙️ Environment**
 - Installation: Kubernetes v1.21
 - Ackee version: v3.2.0

**📋 Additional context**

Is there any way to add the auth source to the mongodb uri like this?
?authSource=admin

**Comment by electerious** [comment]
You need to include the username and password in the MongoDB URL when you have authentication enabled: https://docs.mongodb.com/manual/reference/connection-string/
