### ISSUE TITLE
Reduced UserAgent

### ISSUE THREAD

**Issue by mathe42** [electerious/Ackee#314]
I want to use this issue to adress the change of the UserAgent see https://developer.chrome.com/docs/privacy-sandbox/user-agent

Is this something that could break unique visitor detection? I'm not shure and currently not have the time to look into it so just want to mention it...

**Comment by electerious** [comment]
Thanks for letting me know! It should work fine. Ackee uses the UA in combination with other details to count unique views. The reduced UA still seems to be enough to do so.
