### ISSUE TITLE
JSON Parse error: Unrecognized token '<'

### ISSUE THREAD

**Issue by Daniellop1** [electerious/Ackee#315]
I'm getting this error when I try to log in.
<img width="1440" alt="Captura de Pantalla 2022-01-21 a la(s) 6 21 20 p m" src="https://user-images.githubusercontent.com/44546966/150571623-b63564ba-11d7-4553-8e0b-21232a70fc8f.png">

**Comment by electerious** [comment]
Please provide more details. There's a bug issue template for a reason.

'<' usually means that the server returns HTML which could be because of an incorrect server configuration. Ackee itself never returns HTML via the API endpoint.
