### ISSUE TITLE
Unexpected token A in JSON at position 0

### ISSUE THREAD

**Issue by dco** [electerious/Ackee#318]
vercel

**Comment by dco** [comment]
[POST] /api
19:18:48:10
2022-01-30T11:18:58.210Z 20f499c8-785e-45c2-a892-dad4a44db5b0 Task timed out after 10.01 seconds

**Comment by electerious** [comment]
Can't confirm the issue. Please provide more information. Everything I can say is that Vercel / Serverless functions are sometimes picky. Especially when the site hasn't been visited for a while (cold start). A reload usually fixes these type of errors.

**Comment by artivilla** [comment]
Can you clarify what you mean by reload? I just configured the site and running into the same issue.

**Comment by artivilla** [comment]
In my case my server was returning a 500, you can watch your logs under the [vercel serverless functions](https://vercel.com/docs/concepts/deployments/logs) while trying to log into the site. In my case the ACKEE_MONGODB was setup incorrectly. If you're using Mongodb Atlas then it would be `mongodb+srv://USERNAME:PASSWORD@Cluster0.epank.mongodb.net/test?retryWrites=true&w=majority`

Additional Notes:
`test` can be anything, its the db name but likely doesn't exist the first time you setup your db.
`Cluster0` is the name of the shared cluster in Mongo Atlas.

Hope this helps.

**Comment by flashclub** [comment]
I also encountered this problem, at first I followed the prompt on the page 'Unexpected token A in JSON at position 0' to find a solution, but I didn't find it, then I realized that I should look at the specific error message of the interface, the prompt was 'FUNCTION_INVOCATION_FAILED', then I found this issue #268 ,and eventually I removed the '.' from the mongodb password solved it

**Comment by mihailgaberov** [comment]
Still the same on my side, just deployed it on Vercel and when trying to login with the user/pass from the env. variables, I got this error:
[POST] /api
16:51:14:44
2022-09-26T14:49:57.807Z c4f457a2-b10d-4760-b13f-b43033d30465 Task timed out after 10.02 seconds
2022-09-26T14:51:24.508Z 70f618a2-1375-41ae-a9a8-51983ede1b04 Task timed out after 10.02 seconds

Here are the details:
ACKEE_MONGODB: mongodb+srv://<user>:<pass_without_special_chars>@cluster0.9cz2ddr.mongodb.net/test?retryWrites=true&w=majority

Tried the previous hints, but doesn't seem to work so far.
