### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by ShivamJoker** [electerious/Ackee#319]
**🐣 Is your feature request related to a problem? Please describe.**

Yes currently we can't use react native

**💡 Describe the solution you'd like**

I would love to have library to support react native analytics such as user taps and pages they visit using recat navigation

We can have similar react hook which supports react native as well

**❓ Describe alternatives you've considered**

**📋 Additional context**

Add any other context about the feature request here.

**Comment by electerious** [comment]
There's currently no plugin for React Native, but you can use the API of Ackee to send the data you want to track: https://github.com/electerious/Ackee/blob/master/docs/API.md An official plugin isn't planned. Maybe it's possible to use ackee-tracker or a modified version of ackee-tracker as a base for the plugin.
