### ISSUE TITLE
Using domain style grouping without actual domains

### ISSUE THREAD

**Issue by entrymon** [electerious/Ackee#321]
We have a unique use case, where we do not have sub-domain or different domain but we want to group the analytics data by url.
i.e xyz.com/company/1/home or xyz.com/company/1/posts or xyz.com/company/1/products 
are tracked for company = 1 similar, so when admin of company 1 logs in he can see only events and tracking about his users.

So any option to track events to same instance but group them differently like domaiins.

**Comment by electerious** [comment]
Hey @entrymon, this is currently not possible nor planned. It's only possible to track via different instances/domains, but I agree that this is not perfect.
