### ISSUE TITLE
The `clientId` in the database is always been `null`

### ISSUE THREAD

**Issue by xhemj** [electerious/Ackee#322]
**🐞 Describe the bug**

The `clientId` of almost every record in the database is `null` instead of the normal value.

**💡 Expected behavior**

The value of `clientId` should be something like `0a71bfc3a2645fa7f97ec89d60d7f658f7bda28b582d9390c8844f3aa1503193`.

**⚙️ Environment**
 - Installation: Vercel
 - Ackee version: v3.3.1

**Comment by electerious** [comment]
This should have been fixed in v3.3.1. I can't confirm that this issue still exists.
