### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by mrsnailo** [electerious/Ackee#333]
**🐞 Describe the bug**

I tried to deploy it with netlify. But build process is failing with node module dependency issue. 

**error graphql@16.4.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.16.0 || ^16.0.0 || >=17.0.0". Got "14.9.0"**

**🖼️ Screenshots**
[Screenshot 1](https://ibb.co/2hXqhzF)

**⚙️ Environment**
 Netlify
 - Ackee version: 
v3.4.0

**Comment by adityatelange** [comment]
Have to update 
https://github.com/electerious/Ackee/blob/ba976a89dcde893371b881d5fc4496cfb1c2625c/netlify.toml#L5

**Comment by electerious** [comment]
Fixed in v3.4.1.
