### ISSUE TITLE
Unable to login to Ackee | Vercel Deployment

### ISSUE THREAD

**Issue by adityatelange** [electerious/Ackee#334]
**🐞 Describe the bug**

Unable to login to Ackee. API responds with 
```
An error occurred with your deployment

FUNCTION_INVOCATION_TIMEOUT
```

**📚 To Reproduce**

1. Install Ackee as suggested in docs.
2. Deploy it to vercel.

Repo used to deploy to vercel https://github.com/adityatelange/Ackee-forked. Branch: master

**💡 Expected behavior**

Ackee should login the user opening the dashboard

**🖼️ Screenshots**

![image](https://user-images.githubusercontent.com/21258296/169197699-29c6f956-bc6e-4c26-93d3-75c52b8262ea.png)

![Screenshot from 2022-05-19 09-01-25](https://user-images.githubusercontent.com/21258296/169198651-a38f57b3-0e3f-41db-9f08-fd9d97c7aa0f.png)

**⚙️ Environment**
 - Installation: [e.g. Docker/Docker-Compose/Netlify/Vercel/Manually]: **Vercel**
 - Ackee version: [e.g. v2.1.0]: **v3.4.0**

**📋 Additional context**

**Comment by aidengrong** [comment]
我也是这样

**Comment by electerious** [comment]
FUNCTION_INVOCATION_TIMEOUT isn't unusual for Vercel and can happen when a serveless function hasn't been invoked for a while. It usually fixes itself after a few tries, but I still have no glue why and how to fix it.

**Comment by adityatelange** [comment]
> FUNCTION_INVOCATION_TIMEOUT isn't unusual for Vercel and can happen when a serveless function hasn't been invoked for a while. It usually fixes itself after a few tries, but I still have no glue why and how to fix it.

I'm not sure but this was not happening with previous version https://github.com/adityatelange/Ackee-forked branch primary.
Lost alomost all of stats for 3 days but after reverting back to primary branch everything is fine.
This has been observed with 3.4.0.
Is it because of mongo db queries getting delayed? I'm not sure.

**Comment by adityatelange** [comment]
After experimenting with locations of Vercel deployment, I have the following observations:
For Mongo DB Atlas region is Azure / California (west).
After selecting Serverless Function Region nearer to the mongo region in Vercel, I can somehow log in!
