### ISSUE TITLE
Cant login to dashboard

### ISSUE THREAD

**Issue by mrsnailo** [electerious/Ackee#336]
**🐞 Describe the bug**

I deployed ackee to netlify . Now i Cant login to the dashboard.If its not a bug i have two assumption that i may did wrong.
1)  i may have placed the mongodb connection uri wrongfully 
mongodb+srv://<username>:<password>@cluster0.tktaz.mongodb.net/?retryWrites=true&w=majority
is this ok?

2)  i am confused with the cors header. i set my site url on the variable **ACKEE_ALLOW_ORIGIN**
and set **ACKEE_AUTO_ORIGIN** to true

**⚙️ Environment**
 - Installation: Netlify
 - Ackee version: 3.4.0

**Comment by electerious** [comment]
Is there a log with more details available on Netlify?

You configuration looks correct. Requests to the API should be possible regardless of your CORS configuration as the API is on the same domain.

**Comment by aidengrong** [comment]
我使用3.4.1版本，Netlify部署也是这个提示Response not successful: Received status code 502

**Comment by birjj** [comment]
Looks like an error with the MongoDB URL. If you check your developer tools to see the actual response from the server, you'll get:

<p align="center"><img src="https://user-images.githubusercontent.com/4542461/169666926-eba30267-bfe5-41ab-9474-63fad1e409d9.png" /></p>

Your MongoDB URL needs both a username and a password. For example `mongodb+srv://username:password@url-to-mongodb.com/dbName?retryWrites=true&w=majority`.

**Comment by mrsnailo** [comment]
> Looks like an error with the MongoDB URL. If you check your developer tools to see the actual response from the server, you'll get:
> 
> ![](https://user-images.githubusercontent.com/4542461/169666926-eba30267-bfe5-41ab-9474-63fad1e409d9.png)
> 
> Your MongoDB URL needs a username, a password and the database name. For example `mongodb+srv://username:password@url-to-mongodb.com/dbName?retryWrites=true&w=majority`. It's also possible the URL isn't being set correctly. Is it set as the env variable `ACKEE_MONGODB`?

I did  add the username and password with the URL and set it to **ACKEE_MONGODB** . but still i think the connection is not happening. i tried to connect with mongoshell but couldnot connect to mongobd database..
![mmmmmmm_21-27](https://user-images.githubusercontent.com/46290498/169703141-a9596bb2-1a35-4534-9961-254374f63e23.png)

**Comment by birjj** [comment]
@mrsnailo The URL you've posted here doesn't have the username, password or database name specified. It should look like <code>mongodb+srv://<b>username</b>:<b>password</b>@cluster0.tktaz.mongodb.net/<b>databaseName</b>?retryWrites=true&w=majority</code>. If your password contains special characters they [should be encoded](https://www.mongodb.com/docs/atlas/troubleshoot-connection/#special-characters-in-connection-string-password).

**Comment by birjj** [comment]
@mrsnailo Just to confirm, did changing the URL fix the issue?

**Comment by mrsnailo** [comment]
> @mrsnailo Just to confirm, did changing the URL fix the issue?

Not yet.but thanks i got the idea what i did wrong. I am closing the issue as ackee doesn't have to do anything with the problem. I will learn more about mongodb then deploy again. I am hopeful that will solve the issue.
