### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by marcosmol204** [electerious/Ackee#338]
**🐞 Describe the bug**

Username or password incorrect message when copy paste from enviroment variables

**📚 To Reproduce**

Deploy at netlify

**💡 Expected behavior**

Login

**🖼️ Screenshots**

<img width="377" alt="Screen Shot 1401-03-21 at 14 44 29" src="https://user-images.githubusercontent.com/53741892/173186490-d0a298a4-ba8f-4e37-ac30-c0eb83006d54.png">

**⚙️ Environment**
 - Installation: Netlify
 - Ackee version:  Actual master

**📋 Additional context**

**Comment by electerious** [comment]
Could you solve the problem? Ackee only throws this error when the username and password is incorrect. I'm not sure how to set environment variables on Netlify, but maybe you accidentally quoted them and now the quote is part of the password. I however can confirm that the username and password is set as Ackee would throw a different error when they're missing.

I'm closing this issue as it doesn't seem to be a issue of Ackee itself.
