### ISSUE TITLE
Unexpected token 'A', "An error o"... is not valid JSON

### ISSUE THREAD

**Issue by towindback** [electerious/Ackee#345]
![image](https://user-images.githubusercontent.com/97789192/200573979-e1000456-dbd2-4ea1-95f8-fa279cab4258.png)
It is deploy on vercel, I don't konw why appear this situation.

**Comment by electerious** [comment]
Please take a look at the Vercel log for more details. You can also find the full error message in the network inspector of your browser, which I need to know before I can help. Will close the issue as long as the details are missing.
