### ISSUE TITLE
Show more data in the UI

### ISSUE THREAD

**Issue by electerious** [electerious/Ackee#35]
Ackee [tracks more data](https://github.com/electerious/Ackee/blob/master/docs/records.md#parameters) (optionally) than it currently shows in the UI. The following data should be available via API endpoints and as visualised cards in the UI.

- [x] siteLocation (page views)
- [x] siteLanguage (languages)
- [x] screenWidth and screenHeight (screens -> dimensions)
- [ ] screenColorDepth (screens -> colors)
- [x] deviceName and deviceManufacturer (devices -> _)
- [x] osName and osVersion (devices -> operating systems)
- [x] browserName and browserVersion (browsers -> _)
- [x] browserWidth and browserHeight (browser -> dimensions)
- [x] Visit duration

The initial version of Ackee only shows site visits and referrers.

**Comment by chrkaatz** [comment]
Visit duration would be a nice feature. Do you have an Idea on how to do this?

**Comment by electerious** [comment]
Visit duration will be the next data to show in the UI: https://twitter.com/electerious/status/1175403264805941248

**Comment by electerious** [comment]
Sizes (browser width/height, screen width/height) will be the next data to show in the UI: https://twitter.com/getackee/status/1229021084399345664

**Comment by electerious** [comment]
@RomainCscn added browsers, devices and operating systems to the UI 👏 They will be part of the next version.

**Comment by electerious** [comment]
Closing this issue. "screenColorDepth (screens -> colors)" won't make it into the UI as I don't think it's useful for anyone. Everything else is finally implemented.
