### ISSUE TITLE
Trouble Signing In to app. Received status code 502

### ISSUE THREAD

**Issue by LublubXT** [electerious/Ackee#356]
Hi, I think I got everything set up correctly with netlify. When I sign in, I get an error `Response not successful: Received status code 502`. 

First, I made my MongoDB database accessible anywhere.
Second, I set my username and password.
Third, I set `ACKEE_ALLOW_ORIGIN` to `*`.
Lastly, I set `ACKEE_AUTO_ORIGIN` to `true`.

Here is a screenshot.

![Group 3](https://user-images.githubusercontent.com/73581388/232223016-7af6dd41-bc1e-4b97-9191-08d30e2dee4f.png)
![Group 2](https://user-images.githubusercontent.com/73581388/232223020-fb438529-0607-484b-bc23-f5ad2c9a749b.png)

Does anyone have an idea what the issue is?

**Comment by electerious** [comment]
No idea why this happens, sorry!

I'm closing the issue as there aren't any responses and because it's not an issue of Ackee itself.

**Comment by ppg00** [comment]
same
