### ISSUE TITLE
Is it possible to integrate the Ackee with NextJS as inbuilt analytics.

### ISSUE THREAD

**Issue by neelhabib** [electerious/Ackee#359]
I want to know if its possible to integrate ackee within a NextJS project as inbuilt analytics dashboard?

**Comment by electerious** [comment]
You can use Ackee in your Next.js projects (there's also a React hook available), but I'm not sure what you mean with "inbuilt analytics dashboard". If you want to show your Ackee statistics in your Next.js app then the API of Ackee might be what you're looking for. You however can't embed the dashboard of Ackee directly.
