### ISSUE TITLE
unrecognized time zone identifier: "Europe/Kyiv"

### ISSUE THREAD

**Issue by volodymyr6** [electerious/Ackee#360]
When I tried to open https://demo.ackee.electorious.com/#
I got this "unrecognized time zone identifier: "Europe/Kyiv"" Tried reloading the page didn't help
P.S Browser: Firefox, OS: Windows 10
![photo](https://github.com/electerious/Ackee/assets/50454903/92cf59fe-c875-4d17-90bd-cdc0c8cbaa6e)

**Comment by electerious** [comment]
See https://github.com/electerious/Ackee/issues/343
