### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by rbren** [electerious/Ackee#41]
Would love to be able to quickly install this in a Kubernetes cluster

**Comment by electerious** [comment]
I'm not a Kubernetes user. Let me know what I can do to make Ackee Kubernetes friendly and I will take a look at it 😊 Help is welcome.

**Comment by rbren** [comment]
Shouldn't be too hard - I can take a crack at it, hopefully this week sometime.

**Comment by jhabdas** [comment]
First step is to swap `localhost` in `index.js` with `0.0.0.0`. In fact, that's required even to use this with Docker Compose. Once you've got Compose nailed down look at https://kompose.io for K8s.

**Comment by suda** [comment]
I created a [Helm chart](https://github.com/suda/ackee-chart) and linked to it in #109 :)

**Comment by electerious** [comment]
The PR has been merged and the docs will be part of the next version 😊
