### ISSUE TITLE
Cors header

### ISSUE THREAD

**Issue by CorentinWanteeed** [electerious/Ackee#42]
Hello !

Your server does not allow CORS policy for requests ? It is stranges for an analytics service ^^ I have this issue : `(Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

How can i make it working ? :)

Thank you

**Comment by electerious** [comment]
My server checks the HTTP origin and only allows request when it's a whitelisted site. You can learn more about the correct CORS configuration in this document: https://github.com/electerious/Ackee/blob/master/docs/SSL%20and%20HTTPS.md#example-configurations

Example CORS headers:

```
Access-Control-Allow-Origin: https://example.com
Access-Control-Allow-Methods: POST, PATCH, OPTIONS
Access-Control-Allow-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type
```
