### ISSUE TITLE
multiple accounts? 

### ISSUE THREAD

**Issue by taurean** [electerious/Ackee#43]
Does Ackee allow for multiple user-accounts tracking different websites? I couldn't tell from the website or documentation. I'm currently using [Matomo](https://matomo.org).

**Comment by electerious** [comment]
Ackee only works with one user and it's not planned to add support for multiple user-accounts. I've already done this in older versions/rewrites and it adds a lot of complexity. Ackee is however lightweight enough to create one Ackee instance per user. All instances can be connected to the same MongoDB.
