### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by hieunc229** [electerious/Ackee#45]
Thanks for this apps.

After installation for testing, I wasn't able to login (since `USERNAME` and `PASSWORD` in `.env` were empty string). 

- I updated `USERNAME` and `PASSWORD`, still unable to login.
- I drop all the database in MongoDB, reinstall Ackee (with updated `USERNAME` and `PASSWORD`), still unable to login
- Also tried set `USERNAME=xxx PASSWORD=xxx` when starting the server

There is so little information about the account, is there anyway to reset the password?
(I am pretty sure the login details matched with the `.env` config)

Thanks

**Comment by hieunc229** [comment]
I tried to log `process.env.USERNAME`, turn out it was override as `root` from somewhere within the app.

**Comment by AlexisJC** [comment]
Hi ! i've a trouble with login me too.
Problem is simple in my case. I found `process.env.USERNAME` is not equal to USERNAME .env parameter but equal to my windows session Username ! So, Maybe Username is reserved process.env parameter overwritten by node.

Simple solution is to use another entry like ACKEE_USERNAME and ACKEE_PASSWORD. I think it's better because USERNAME and PASSWORD were ambiguous, I first thought it was the identifiers for my mongodb instance. (My fault I did not read the doc correctly)

**Comment by electerious** [comment]
This is interesting. Using `ACKEE_USERNAME` and `ACKEE_PASSWORD` could be a solution. Maybe prefixing all environment variables with `ACKEE_` could help to avoid collisions.

**Comment by electerious** [comment]
The `dotenv` documentation explains why this is happening:

```
We will never modify any environment variables that have already been set. In particular, if there is a variable in your .env file which collides with one that already exists in your environment, then that variable will be skipped. This behavior allows you to override all .env configurations with a machine-specific environment, although it is not recommended.
```

This somehow makes sense, but it's annoying when it's not you overwriting the variables.

I will add the prefixes in the next update which should be ready in a few days. Thanks for letting me know!

**Comment by electerious** [comment]
Ready to test on [`develop`](https://github.com/electerious/Ackee/tree/develop). Could somebody give it a try to confirm that it's working? Also available using the `develop` docker tag.

**Comment by hieunc229** [comment]
Thanks for the update. I tested the `develop` branch and it works great (not using Docker)

**Comment by electerious** [comment]
v1.1.0 is now live and includes the `ACKEE_` prefix for all variables.
