### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by zhaowenyuan** [electerious/Ackee#51]
Open test page(ackee-tracker/demos/create.html),A few minutes later report the following error:
ackee-tracker.min.js:1 PATCH http://localhost:3000/domains/d2c55e6e-4dc1-4f78-bfe7-069fe1141fb7/records/20f8c1cd-b680-46e9-b4ce-d5b83b007d45 net::ERR_CONNECTION_REFUSED

**Comment by zhaowenyuan** [comment]
The problem did not appear in v1.2.0.

**Comment by electerious** [comment]
`net::ERR_CONNECTION_REFUSED` usually happens when you open the demo HTML directly without using a server. AJAX requests aren't possible when opening as a file.

> The problem did not appear in v1.2.0.

Sounds good. I will close the issue.
