### ISSUE TITLE
Rename "tracker.js" to avoid it being picked up by adblockers

### ISSUE THREAD

**Issue by Stanko** [electerious/Ackee#53]
Hello, 
Firstly let me thank you for the great work with Ackee. I was looking for simple, self-hosted analytics, and it works perfectly for my usecase.

I had a small problem with the script `tracker.js`, because of the name, it is picked up by adblocker filters. Maybe it makes sense to rename it to `ackee.js` or something along those lines.

Cheers!

**Comment by electerious** [comment]
Naming it `tracker.js` wasn't clever 😃 `ackee.js` might work for now, but I'm sure it will be blocked someday, too.

I will add an option to change the name of the script. This way everyone can pick a custom name to avoid that the script will be blocked.

Tip: You can also use [`ackee-tracker`](https://github.com/electerious/ackee-tracker) as a module. This way you don't need to request a script that could be blocked.

**Comment by Stanko** [comment]
Oh, I wasn't aware of the `ackee-tracker`, good stuff. Allowing user to select the name is the perfect solution.

Btw I ended up using `ack` as the subdomain for ackee. Started with `analytics` subodomain but it got blocked instantly 😄

**Comment by markuspoerschke** [comment]
@electerious I think this issue can be closed, since it is available in `v1.4.0`.

**Comment by electerious** [comment]
Yes. It's now part of v1.4: https://github.com/electerious/Ackee#tracker
