### ISSUE TITLE
Please add content-type headers to static assets

### ISSUE THREAD

**Issue by bayi** [electerious/Ackee#56]
Currently Ackee isnt adding Content-Type headers for .js and .css files.

Im using traefik to automatically server my containers and get auto ssl certs.

Treafik automatically adds a "text/plan" content type headers for every resource that doesnt have any content-type headers. 

This currently breaks the frontend styles, the css is simply ignored by Chrome and i get also problems with the tracker in some browsers ( but in chrome its fine with text/plain ).

**Comment by electerious** [comment]
Correct content-type headers have been added to the develop branch lately. They're part of the next release :)

https://github.com/electerious/Ackee/blob/develop/CHANGELOG.md

**Comment by electerious** [comment]
You can use the `develop` docker tag if you want to take a look at it: https://cloud.docker.com/u/electerious/repository/docker/electerious/ackee

**Comment by bayi** [comment]
Thank you very much
