### ISSUE TITLE
Monthly reports to Client

### ISSUE THREAD

**Issue by Kulcanhez** [electerious/Ackee#59]
Hello! Thank you for your work. Is it possible to do a monthly report including a single website for a client?

**Comment by electerious** [comment]
Hey @Kulcanhez, are you talking about a way to export a report or about the possibility to [view previous weeks/months](https://github.com/electerious/Ackee/issues/39). Could you specify the data you're looking for more precisely?

**Comment by Kulcanhez** [comment]
I'm referring to something like this: https://support.google.com/analytics/answer/6081893?hl=en

**Comment by electerious** [comment]
It's not planned to add this feature to Ackee, but it's possible to use the API to generate such reports (after [previous weeks/months](https://github.com/electerious/Ackee/issues/39) are supported). Maybe someone wants to build a tool for this :)

**Comment by BetaHuhn** [comment]
Hey, I just finished building a CLI tool called [ackee-report](https://github.com/BetaHuhn/ackee-report) which solves this issue. 

It lets you create monthly (or in any interval) reports for any one of your websites and send them to multiple email addresses. You can create multiple reports for different websites and recipients.

It requires minimal knowledge of the command line and cron (all explained in the [README](https://github.com/BetaHuhn/ackee-report#%EF%B8%8F-configuration)) and you have to use your own email service like gmail, SendGrid or any other service which supports SMTP.

CC @Kulcanhez

**Comment by Kulcanhez** [comment]
@BetaHuhn amazing work! 😄 I would love to have a screenshot of how the email looks and see how we can improve it.

**Comment by BetaHuhn** [comment]
Right now it's just simple text, but I am already working on mimicking the design of the Ackee UI. For now it's just going to use Ackee's color scheme.

 The email is just a [ejs template](https://github.com/BetaHuhn/ackee-report/blob/master/src/templates/ackee.ejs) which gets rendered with the data from the API. The plan is to create different templates which you can choose from.

You are very welcome to create your own and submit them via a PR! Also let me know if there's something else missing in the tool.

Here's is screenshot:
![Email preview](https://user-images.githubusercontent.com/51766171/97429248-743c8e80-1917-11eb-979b-c7fe91284172.png)

**Comment by Kulcanhez** [comment]
> Right now it's just simple text, but I am already working on mimicking the design of the Ackee UI. For now it's just going to use Ackee's color scheme.
> 
> The email is just a [ejs template](https://github.com/BetaHuhn/ackee-report/blob/master/src/templates/ackee.ejs) which gets rendered with the data from the API. The plan is to create different templates which you can choose from.
> 
> You are very welcome to create your own and submit them via a PR! Also let me know if there's something else missing in the tool.
> 
> Here's a screenshot:
> ![Email preview](https://user-images.githubusercontent.com/51766171/97429248-743c8e80-1917-11eb-979b-c7fe91284172.png)
> 
> Edit: fix typo

For me, it sounds amazing and feels really complete. I was also thinking in use Ackee design feel, so I'm excited to see the look. 😄

**Comment by electerious** [comment]
That's awesome! Thanks a lot for creating such an amazing tool for Ackee!

**Comment by BetaHuhn** [comment]
Thanks! I just released a new [version](https://www.npmjs.com/package/ackee-report/v/0.4.0) which now uses Ackee's color scheme and a overall cleaner structure in the report:

![email preview](https://user-images.githubusercontent.com/51766171/97487338-074be780-195d-11eb-97a8-09f5b6d2007a.png)

I still need to work on how to display the pages, referrers and other detailed data in a cleaner way, but I think for now it's good enough 😄

**Comment by Kulcanhez** [comment]
@BetaHuhn looks much better!! Thank you for your amazing contribution! 🚀
