### ISSUE TITLE
Better install documentation

### ISSUE THREAD

**Issue by BrookeDot** [electerious/Ackee#62]
Hi there, 

I've tried to install this on Digital Ocean's Docker container and keep having trouble. I'm new to docker (and docker compose) so any additional documentation would be helpful.  I come from a LEMP background so things like do I need to install NGINX, what port should I listen on, etc?

Right now I'm getting one of two errors after cloning the repo. If I first run `docker compose up` things hang at:

```
mongo    | 2019-11-16T22:19:35.323+0000 I  SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
```

if I quick then re-open they hang at:
```
mongo    | 2019-11-16T23:08:22.642+0000 I  NETWORK  [conn3] received client metadata from xxx.xx.xxx.xx:44584 conn3: { driver: { name: "nodejs", version: "3.3.3" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-70-generic" }, platform: "Node.js v10.17.0, LE, mongodb-core: 3.3.3" }
```

Any advice or links to external documentation on how to get started with Ackee?

**Comment by BrookeDot** [comment]
Okay after looking at the SSL/HTTPS documentation I installed NGINX and things are now working as expected. However, let's still work to improve the documentation for those of us who are new to how Docker works :)

**Comment by electerious** [comment]
I've just added the related guides (SSL/HTTPS and CORS headers) to the get started guide: https://github.com/electerious/Ackee/commit/47d87cc6d5c8d50845646c0680998f4d4ebe34c9

This might help a bit, but I agree that a complete guide (that also covers NGINX) is necessary.

**Comment by BrookeDot** [comment]
Thanks for that update, I do think it brings a lot of clarity. I just submitted #63  to hopefully make things a bit better too.

**Comment by lucasdcrk** [comment]
Wouldn't it be better to use Github's Wiki feature for documentation?

**Comment by electerious** [comment]
@lucasdcrk Github's Wiki isn't part of the repository/git which makes them a bit harder to manage.  I personally never liked them. Is there anything the Wiki does better than normal markdown pages?

**Comment by lucasdcrk** [comment]
@electerious Navigating between pages/files mainly (it's hard to explain but it feels weird to navigate in markdown files for documentation).
If you want something markdown based and versionable https://vuepress.vuejs.org/ does a pretty good job!

**Comment by electerious** [comment]
@lucasdcrk Good point. Navigating between markdown files is definitely not the best way. Might be worth a try.

**Comment by electerious** [comment]
There's now a dedicated site for the documentation 😊 https://docs.ackee.electerious.com/#/
