### ISSUE TITLE
Mixed content warnings when loading some referrers favicon

### ISSUE THREAD

**Issue by BrookeDot** [electerious/Ackee#64]
My install runs over https, and I noticed a Mixed Content Warning in my browser (Firefox). After some investigation I tracked this down to the favicon of a referrer which used the `http` protocol. My browser blocked this icon and the default images is shown in the install but wanted to mention it here. 

<img width="1459" alt="Screen Shot 2019-11-19 at 9 30 16 PM" src="https://user-images.githubusercontent.com/150348/69211731-de4b9180-0b13-11ea-94f2-f8a7d5c491be.png">

I'm not sure what the best solution is, perhaps checking to see if it can be loaded over `https` and if not falling back may make the most since but that complicates the logic a bit.  Another solution could be to force https but that would surely break some favicons.

**Comment by electerious** [comment]
I don't think this is problematic. The favicons are just visual enhancements. Ackee is also just guessing that there's a favicon at `/favicon.ico` which isn't always the case.

Upgrading them to https: Could work, but when the referrer is http than there's a small chance that the site is available via the https (would be a badly configured server in this case).

**Comment by BrookeDot** [comment]
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) this is type of warning from the browser is known as a passive mixed content warning. The biggest risks appears to be revealing the URL and allowing some tracking of an otherwise private Ackee install to the third-party site:
>The attacker could also infer information about the user's activities by watching which images are served to the user; often images are only served on a specific page within a website. If the attacker observes HTTP requests to certain images, they could determine which webpage the user is visiting.

I looked into a few solutions and found a node package [favrat ](https://www.npmjs.com/package/favrat) as well as some solutions in other languages. It seems in most cases the idea is to cURL the site, see if there's a favicon and you get a 200 response then do something with the icon. 

By far the easiest method is to use the Google API but we should keep Google out of Ackee by all means :)
http://s2.googleusercontent.com/s2/favicons?domain_url=http://github.com

Let me know if I can be of any other assistance here.

**Comment by electerious** [comment]
The solutions aren't very satisfying, so I will stay with the current implementation. I don't think that revealing the URL of the Ackee instance is problematic enough.

**Comment by BrookeDot** [comment]
Thanks for the update here. I found an easy way to prevent this (but also not show icons at all over HTTP) is to add the following to the NGINX config:

`        add_header          Content-Security-Policy "block-all-mixed-content";`

I totally get wanting to show icons over http so blocking things at the server level seems like a good way for users, like me, who would rather not show mixed content warnings and instead always have https.
