### ISSUE TITLE
feature request: installation on shared host? (@web-hosting provider)

### ISSUE THREAD

**Issue by supervisitor** [electerious/Ackee#65]
is there a port with mysql and index page to install it on a shared host?

it would be nice because the analysis view is better than Matomo and sufficient for the marketing department.

**Comment by electerious** [comment]
It's currently not planned to add support for MySQL. I'm also not sure if it's possible to run Ackee on a shared host because of Node.js.

**Comment by PPMary** [comment]
Node.js will probably be the least of your problems. But the approach is good, can I contribute something?

**Comment by electerious** [comment]
@PPMary Sure, but please open an issue first so we can discuss what want to implement.
