### ISSUE TITLE
WordPress Plugin

### ISSUE THREAD

**Issue by BrookeDot** [electerious/Ackee#67]
Hi there, 

This isn't an issue, but I wanted to let you know I created a VERY basic WordPress plugin to add tracking from WP Admin without needing to edit theme files:
https://github.com/BrookeDot/ackee-wp

I expect to document things a bit better and blog about it but wanted to let you know.

**Comment by BrookeDot** [comment]
<img width="998" alt="Screen Shot 2019-12-14 at 5 22 56 PM" src="https://user-images.githubusercontent.com/150348/70856725-990e4b80-1e96-11ea-99d0-e2fd52ed84a3.png">

**Comment by electerious** [comment]
That's great! I will keep the issue open as a reminder for myself to tweet about it. Please let me know when you think it's ready (the readme looks a bit unformatted right now) :)

**Comment by BrookeDot** [comment]
Yeah, the `Readme.md `is just a copy of the WordPress formatted  `readme.txt` which annoyingly uses its own markdown format.

**Comment by BrookeDot** [comment]
Also do you mind if I use some of the visual aspects from the Ackee website for the assets submitted to the WordPress.org directory? For example the banner, and icon shown on the plugin page..

**Comment by electerious** [comment]
Sure, you can use the assets.

**Comment by BrookeDot** [comment]
I cleaned up the ReadMe on GitHub and also wrote a blog post about this on my own blog:
https://brooke.codes/2019/12/29/introducing-ackee-wp/

The plugin has been submitted to the WordPress.org plugin team for review but until it's accepted in the official repository it can be used from my GitHub repository.

**Comment by BrookeDot** [comment]
The plugin is now on WordPress.org as Soapberry:
https://wordpress.org/plugins/soapberry/

I was asked to change the name to comply with the directories guideline of project names:
https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#17-plugins-must-respect-trademarks-copyrights-and-project-names

**Comment by electerious** [comment]
Awesome! I will add it to the list of related modules 😊

**Comment by electerious** [comment]
Done ✅
