### ISSUE TITLE
[Feature Request] Add `Deploy to Heroku` button to README.md

### ISSUE THREAD

**Issue by aleccool213** [electerious/Ackee#72]
## Feature Request

Hi there! Great application! I really love how simple and privacy focused it is.

It would be great to have a `Deploy to Heroku` button, would help drive up adoption!

[Documentation](https://devcenter.heroku.com/articles/heroku-button#requirements)

**Comment by electerious** [comment]
A "Deploy to Heroku" button would be cool, but I guess that #73 should be finished first. Help is welcome!

**Comment by electerious** [comment]
Will be part of `v1.4.3`.
