### ISSUE TITLE
[Feature Request] Environment Variables to adjust CORS header values

### ISSUE THREAD

**Issue by aleccool213** [electerious/Ackee#73]
## Feature Request

I have read the [docs](https://github.com/electerious/Ackee/blob/master/docs/CORS%20headers.md) concerning the CORS header values and [how to configure them using a reverse proxy](https://github.com/electerious/Ackee/blob/master/docs/SSL%20and%20HTTPS.md#advanced-configuration). For myself, my need for a reverse proxy is low, I am requesting the ability to add these headers to all requests when new environment variables are added and set. 

For e.g.

```javascript
res.addHeader("Access-Control-Allow-Origin", "https://myackeehostedinstance.herokuapp.com")
```

**Comment by electerious** [comment]
Hey @aleccool213, the reverse proxy is required for both HTTPS and CORS. My plan was to keep the server related logic away from Ackee as everyone has a different setup.

How are you adding HTTPS?

**Comment by aleccool213** [comment]
> My plan was to keep the server related logic away from Ackee as everyone has a different setup.

This is a smart separation of concerns and I generally agree with this.

Unfortunately for me, I am running Ackee on Heroku. It provides a free SSL certificate for free dynos.

![Screenshot at Dec 16 08-45-06](https://user-images.githubusercontent.com/6475934/70911750-8869ec80-1fe0-11ea-8e37-53cc613d2388.png)

Albeit, not a strict cert for my specific domain.

**Comment by aleccool213** [comment]
Update on this, I tried getting https://github.com/narr/heroku-nginx-node-example up and running but it is super old. Need more time to debug why that wasn't working, or try it from scratch myself.

**Comment by electerious** [comment]
Will be part of `v1.4.3`.

**Comment by electerious** [comment]
Should `ACKEE_ALLOW_ORIGIN` be part of [the app.json](https://github.com/electerious/Ackee/blob/master/app.json#L12) so it can be configured by the user?
