### ISSUE TITLE
Travis CI builds are not linked to pull request details

### ISSUE THREAD

**Issue by aleccool213** [electerious/Ackee#75]
![Screenshot at Jan 02 16-19-51](https://user-images.githubusercontent.com/6475934/71693971-c8b8c100-2d7b-11ea-9808-2abd1b9065c6.png)

I should get a link to the linked travis ci build, not just the coveralls build in pull requests.

**Comment by electerious** [comment]
Not sure if it's working now, but I've added the newest Travis GitHub app. "Build pushed pull request" itself was already activated on Travis.

**Comment by aleccool213** [comment]
IT WORKS

![Screenshot at Jan 11 11-49-20](https://user-images.githubusercontent.com/6475934/72207574-72790b80-3468-11ea-80ca-cff30d3404c7.png)
