### ISSUE TITLE
Integration in python app

### ISSUE THREAD

**Issue by alicelovalvo** [electerious/Ackee#86]
Hi,
I'm trying to use your web app to track users of another web app on herokuapp developed in python. I followed all the instruction, but it doesn't work.
I add the following code in my code:

external_scripts = ["https://covid19-ackee-server.herokuapp.com/tracker.js"]
app = dash.Dash(__name__, external_stylesheets=external_stylesheets, external_scripts=external_scripts)
server = app.server

Is there something that I forget?

Thank in advance!

**Comment by electerious** [comment]
I can't tell you the correct configuration for your python app, but you can show me the output (HTML) and I will let you know if it looks correct :)

Also: Is there an error or can you specify what exactly isn't working?
