### ISSUE TITLE
Can Ackee be hosted on a free Heroku dyno?

### ISSUE THREAD

**Issue by remi2j** [electerious/Ackee#98]
Hello 👋

I know Encki can technically run on a free Heroku dyno. But they are [known for sleeping](https://devcenter.heroku.com/articles/free-dyno-hours#dyno-sleeping) after some inactivity.

So if my site doesn't have any visitors for a while, what happens? Does it restart fast enough for Ackee to work? Or is the session untracked?

Thanks

**Comment by electerious** [comment]
It takes a while to compile the front-end (JS and CSS), but that happens in the background and the API should be available almost instantly as long as MongoDB is ready.

Could be worth a try. Please let me know if it works! :)

**Comment by remi2j** [comment]
I tried it, the first request takes 13 seconds to load and ends up successful. I guess the delay is caused by Heroku setting up the dyno, not the node  API.

I don't mind the delay to load the front-end. It's nice to know we can have self-hosted analytics for free. Thanks!
